"""Add AR write-offs support

Revision ID: 0efaf8fb0263
Revises: 0b037f156aa0
Create Date: 2025-06-24 20:13:49.042667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0efaf8fb0263'
down_revision: Union[str, None] = '0b037f156aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ar_writeoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('original_invoice_id', sa.Integer(), nullable=False),
    sa.Column('ar_transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('linked_gl_journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=False),
    sa.Column('writeoff_date', sa.Date(), nullable=False),
    sa.Column('writeoff_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('reason_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ar_transaction_type_id'], ['ar_transaction_types.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['linked_gl_journal_entry_id'], ['gl_journal_entries.id'], ),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['ar_transactions.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number', 'company_id', name='uq_writeoff_document_company')
    )
    op.create_index(op.f('ix_ar_writeoffs_id'), 'ar_writeoffs', ['id'], unique=False)
    op.add_column('ar_defaults', sa.Column('default_bad_debt_gl_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ar_defaults', 'gl_accounts', ['default_bad_debt_gl_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ar_defaults', type_='foreignkey')
    op.drop_column('ar_defaults', 'default_bad_debt_gl_account_id')
    op.drop_index(op.f('ix_ar_writeoffs_id'), table_name='ar_writeoffs')
    op.drop_table('ar_writeoffs')
    # ### end Alembic commands ###
