"""Add BOM models

Revision ID: 222b241a2d56
Revises: 0efaf8fb0263
Create Date: 2025-06-25 01:24:12.117234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222b241a2d56'
down_revision: Union[str, None] = '0efaf8fb0263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('default_wip_gl_account_id', sa.Integer(), nullable=True),
    sa.Column('default_material_usage_gl_account_id', sa.Integer(), nullable=True),
    sa.Column('default_manufacturing_overhead_gl_account_id', sa.Integer(), nullable=True),
    sa.Column('default_scrap_gl_account_id', sa.Integer(), nullable=True),
    sa.Column('next_mo_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['default_manufacturing_overhead_gl_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['default_material_usage_gl_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['default_scrap_gl_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['default_wip_gl_account_id'], ['gl_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_index(op.f('ix_bom_defaults_id'), 'bom_defaults', ['id'], unique=False)
    op.create_table('bom_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('parent_item_id', sa.Integer(), nullable=False),
    sa.Column('bom_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('revision', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('quantity_per_batch', sa.Numeric(), nullable=True),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_code', 'company_id', name='uq_bom_code_company'),
    sa.UniqueConstraint('parent_item_id', 'revision', 'company_id', name='uq_bom_item_revision_company')
    )
    op.create_index(op.f('ix_bom_headers_id'), 'bom_headers', ['id'], unique=False)
    op.create_table('bom_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_header_id', sa.Integer(), nullable=False),
    sa.Column('component_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Numeric(), nullable=False),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=True),
    sa.Column('scrap_percentage', sa.Numeric(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('is_phantom', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bom_header_id'], ['bom_headers.id'], ),
    sa.ForeignKeyConstraint(['component_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_components_id'), 'bom_components', ['id'], unique=False)
    op.create_table('manufacturing_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('bom_header_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity_to_manufacture', sa.Numeric(), nullable=False),
    sa.Column('quantity_completed', sa.Numeric(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('linked_gl_journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bom_header_id'], ['bom_headers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['linked_gl_journal_entry_id'], ['gl_journal_entries.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_manufacturing_orders_id'), 'manufacturing_orders', ['id'], unique=False)
    op.create_table('manufacturing_order_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturing_order_id', sa.Integer(), nullable=False),
    sa.Column('component_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Numeric(), nullable=False),
    sa.Column('quantity_issued', sa.Numeric(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['component_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['manufacturing_order_id'], ['manufacturing_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturing_order_components_id'), 'manufacturing_order_components', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manufacturing_order_components_id'), table_name='manufacturing_order_components')
    op.drop_table('manufacturing_order_components')
    op.drop_index(op.f('ix_manufacturing_orders_id'), table_name='manufacturing_orders')
    op.drop_table('manufacturing_orders')
    op.drop_index(op.f('ix_bom_components_id'), table_name='bom_components')
    op.drop_table('bom_components')
    op.drop_index(op.f('ix_bom_headers_id'), table_name='bom_headers')
    op.drop_table('bom_headers')
    op.drop_index(op.f('ix_bom_defaults_id'), table_name='bom_defaults')
    op.drop_table('bom_defaults')
    # ### end Alembic commands ###
