"""add bug_reports table

Revision ID: 2887a06d6aa1
Revises: b7b664b3df79
Create Date: 2025-08-02 01:02:07.175581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2887a06d6aa1'
down_revision: Union[str, None] = 'b7b664b3df79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('feedback_comments', 'is_internal',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('feedback_requests', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feedback_requests', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('gl_journal_entry_lines', 'is_tax_line',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('gl_transaction_types', 'is_tax_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('gl_transaction_types', 'tax_calculation_method',
               existing_type=postgresql.ENUM('NONE', 'INCLUSIVE', 'EXCLUSIVE', name='taxcalculationmethod'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gl_transaction_types', 'tax_calculation_method',
               existing_type=postgresql.ENUM('NONE', 'INCLUSIVE', 'EXCLUSIVE', name='taxcalculationmethod'),
               nullable=False)
    op.alter_column('gl_transaction_types', 'is_tax_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('gl_journal_entry_lines', 'is_tax_line',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('feedback_requests', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feedback_requests', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feedback_comments', 'is_internal',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('feedback_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
