"""Add notes, reorder_level, and reorder_quantity to inventory_items

Revision ID: 32fe6acb0a24
Revises: ec20384557f7
Create Date: 2025-07-25 12:59:15.996395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32fe6acb0a24'
down_revision: Union[str, None] = 'ec20384557f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('inventory_items', sa.Column('reorder_level', sa.Numeric(), nullable=True))
    op.add_column('inventory_items', sa.Column('reorder_quantity', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'reorder_quantity')
    op.drop_column('inventory_items', 'reorder_level')
    op.drop_column('inventory_items', 'notes')
    # ### end Alembic commands ###
