"""Add Order Entry models

Revision ID: 36ae99f8ab8e
Revises: d2924ef62137
Create Date: 2025-06-14 00:00:12.082448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36ae99f8ab8e'
down_revision: Union[str, None] = 'd2924ef62137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('default_so_status', sa.String(), nullable=True),
    sa.Column('default_po_status', sa.String(), nullable=True),
    sa.Column('default_grv_status', sa.String(), nullable=True),
    sa.Column('next_so_number', sa.Integer(), nullable=True),
    sa.Column('next_po_number', sa.Integer(), nullable=True),
    sa.Column('next_grv_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_index(op.f('ix_order_defaults_id'), 'order_defaults', ['id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('delivery_address_warehouse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['delivery_address_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_table('goods_received_vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('grv_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ap_invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ap_invoice_id'], ['ap_transactions.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_received_vouchers_id'), 'goods_received_vouchers', ['id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(), nullable=True),
    sa.Column('unit_price', sa.Numeric(), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(), nullable=True),
    sa.Column('tax_type_id', sa.Integer(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(), nullable=True),
    sa.Column('line_total', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_id'), 'purchase_order_lines', ['id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sales_representative_id', sa.Integer(), nullable=True),
    sa.Column('ar_invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ar_invoice_id'], ['ar_transactions.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sales_representative_id'], ['sales_representatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_orders_id'), 'sales_orders', ['id'], unique=False)
    op.create_table('goods_received_voucher_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grv_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(), nullable=False),
    sa.Column('line_total', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['grv_id'], ['goods_received_vouchers.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_received_voucher_lines_id'), 'goods_received_voucher_lines', ['id'], unique=False)
    op.create_table('sales_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(), nullable=False),
    sa.Column('quantity_invoiced', sa.Numeric(), nullable=True),
    sa.Column('unit_price', sa.Numeric(), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(), nullable=True),
    sa.Column('tax_type_id', sa.Integer(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(), nullable=True),
    sa.Column('line_total', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_lines_id'), 'sales_order_lines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_order_lines_id'), table_name='sales_order_lines')
    op.drop_table('sales_order_lines')
    op.drop_index(op.f('ix_goods_received_voucher_lines_id'), table_name='goods_received_voucher_lines')
    op.drop_table('goods_received_voucher_lines')
    op.drop_index(op.f('ix_sales_orders_id'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_purchase_order_lines_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_goods_received_vouchers_id'), table_name='goods_received_vouchers')
    op.drop_table('goods_received_vouchers')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_order_defaults_id'), table_name='order_defaults')
    op.drop_table('order_defaults')
    # ### end Alembic commands ###
