"""add_oe_defaults_fields

Revision ID: 71847c0f0bef
Revises: 32fe6acb0a24
Create Date: 2025-07-25 15:05:43.329093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71847c0f0bef'
down_revision: Union[str, None] = '32fe6acb0a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_defaults', sa.Column('default_currency_code', sa.String(), nullable=True))
    op.add_column('order_defaults', sa.Column('default_payment_terms', sa.String(), nullable=True))
    op.add_column('order_defaults', sa.Column('default_sales_representative_id', sa.Integer(), nullable=True))
    op.add_column('order_defaults', sa.Column('default_warehouse_id', sa.Integer(), nullable=True))
    op.add_column('order_defaults', sa.Column('auto_generate_order_numbers', sa.Boolean(), nullable=True))
    op.add_column('order_defaults', sa.Column('sales_order_number_prefix', sa.String(), nullable=True))
    op.add_column('order_defaults', sa.Column('purchase_order_number_prefix', sa.String(), nullable=True))
    op.add_column('order_defaults', sa.Column('grv_number_prefix', sa.String(), nullable=True))
    op.add_column('order_defaults', sa.Column('require_approval_for_orders', sa.Boolean(), nullable=True))
    op.add_column('order_defaults', sa.Column('order_approval_limit', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'order_defaults', 'sales_representatives', ['default_sales_representative_id'], ['id'])
    op.create_foreign_key(None, 'order_defaults', 'warehouses', ['default_warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_defaults', type_='foreignkey')
    op.drop_constraint(None, 'order_defaults', type_='foreignkey')
    op.drop_column('order_defaults', 'order_approval_limit')
    op.drop_column('order_defaults', 'require_approval_for_orders')
    op.drop_column('order_defaults', 'grv_number_prefix')
    op.drop_column('order_defaults', 'purchase_order_number_prefix')
    op.drop_column('order_defaults', 'sales_order_number_prefix')
    op.drop_column('order_defaults', 'auto_generate_order_numbers')
    op.drop_column('order_defaults', 'default_warehouse_id')
    op.drop_column('order_defaults', 'default_sales_representative_id')
    op.drop_column('order_defaults', 'default_payment_terms')
    op.drop_column('order_defaults', 'default_currency_code')
    # ### end Alembic commands ###
