"""Add GL models

Revision ID: 7c9a5381f90f
Revises: c6e5f8a9b3d1
Create Date: 2025-06-12 10:23:43.870185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9a5381f90f'
down_revision: Union[str, None] = 'c6e5f8a9b3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gl_defaults_company_id'), table_name='gl_defaults')
    op.create_unique_constraint(None, 'gl_defaults', ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gl_defaults', type_='unique')
    op.create_index(op.f('ix_gl_defaults_company_id'), 'gl_defaults', ['company_id'], unique=True)
    # ### end Alembic commands ###
