"""Add tax control account to GL transaction types

Revision ID: 802fdf577b87
Revises: c2dcdf44d4c4
Create Date: 2025-07-29 20:59:24.409456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802fdf577b87'
down_revision: Union[str, None] = 'c2dcdf44d4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gl_transaction_types', sa.Column('default_tax_control_account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_gl_transaction_types_name'), 'gl_transaction_types', ['name'], unique=False)
    op.create_foreign_key(None, 'gl_transaction_types', 'gl_accounts', ['default_tax_control_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gl_transaction_types', type_='foreignkey')
    op.drop_index(op.f('ix_gl_transaction_types_name'), table_name='gl_transaction_types')
    op.drop_column('gl_transaction_types', 'default_tax_control_account_id')
    # ### end Alembic commands ###
