"""Create GL models: GLAccount, GLJournalEntry, GLJournalEntryLine, GLTransactionType, GLDefaults

Revision ID: b7d8e9f4c5a2
Revises: 393eb9761ada
Create Date: 2025-06-11 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d8e9f4c5a2'
down_revision: Union[str, None] = '393eb9761ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gl_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('parent_account_id', sa.Integer(), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_control_account', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_account_id'], ['gl_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_code', 'company_id', name='uq_glaccount_code_company')
    )
    op.create_index(op.f('ix_gl_accounts_account_code'), 'gl_accounts', ['account_code'], unique=False)
    op.create_index(op.f('ix_gl_accounts_id'), 'gl_accounts', ['id'], unique=False)
    
    op.create_table('gl_transaction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('default_debit_account_id', sa.Integer(), nullable=True),
    sa.Column('default_credit_account_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['default_credit_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['default_debit_account_id'], ['gl_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'company_id', name='uq_gltransactiontype_name_company')
    )
    op.create_index(op.f('ix_gl_transaction_types_id'), 'gl_transaction_types', ['id'], unique=False)
    
    op.create_table('gl_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('retained_earnings_account_id', sa.Integer(), nullable=True),
    sa.Column('default_cash_account_id', sa.Integer(), nullable=True),
    sa.Column('default_ar_control_account_id', sa.Integer(), nullable=True),
    sa.Column('default_ap_control_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['default_ap_control_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['default_ar_control_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['default_cash_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['retained_earnings_account_id'], ['gl_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gl_defaults_id'), 'gl_defaults', ['id'], unique=False)
    op.create_index(op.f('ix_gl_defaults_company_id'), 'gl_defaults', ['company_id'], unique=True)
    
    op.create_table('gl_journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('posted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gl_journal_entries_id'), 'gl_journal_entries', ['id'], unique=False)
    
    op.create_table('gl_journal_entry_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('gl_account_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['gl_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['gl_journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gl_journal_entry_lines_id'), 'gl_journal_entry_lines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gl_journal_entry_lines_id'), table_name='gl_journal_entry_lines')
    op.drop_table('gl_journal_entry_lines')
    op.drop_index(op.f('ix_gl_journal_entries_id'), table_name='gl_journal_entries')
    op.drop_table('gl_journal_entries')
    op.drop_index(op.f('ix_gl_defaults_company_id'), table_name='gl_defaults')
    op.drop_index(op.f('ix_gl_defaults_id'), table_name='gl_defaults')
    op.drop_table('gl_defaults')
    op.drop_index(op.f('ix_gl_transaction_types_id'), table_name='gl_transaction_types')
    op.drop_table('gl_transaction_types')
    op.drop_index(op.f('ix_gl_accounts_id'), table_name='gl_accounts')
    op.drop_index(op.f('ix_gl_accounts_account_code'), table_name='gl_accounts')
    op.drop_table('gl_accounts')
    # ### end Alembic commands ###
