"""add grv clearing account to inventory defaults

Revision ID: c2dcdf44d4c4
Revises: 71847c0f0bef
Create Date: 2025-07-26 20:19:16.386332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2dcdf44d4c4'
down_revision: Union[str, None] = '71847c0f0bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_defaults', sa.Column('default_grv_clearing_gl_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_defaults', 'gl_accounts', ['default_grv_clearing_gl_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_defaults', type_='foreignkey')
    op.drop_column('inventory_defaults', 'default_grv_clearing_gl_account_id')
    # ### end Alembic commands ###
