"""Add tax and forex support to transactions

Revision ID: cb021f26c404
Revises: cb8eefe9b000
Create Date: 2025-06-29 22:42:41.335938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb021f26c404'
down_revision: Union[str, None] = 'cb8eefe9b000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('rate_date', sa.Date(), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_id', 'rate_date', 'company_id', name='uq_exchange_rate_date')
    )
    op.create_table('forex_gain_loss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('gain_loss_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gl_journal_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['gl_journal_entry_id'], ['gl_journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ap_transaction_tax_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ap_transaction_id', sa.Integer(), nullable=True),
    sa.Column('tax_type_id', sa.Integer(), nullable=True),
    sa.Column('taxable_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('base_currency_tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['ap_transaction_id'], ['ap_transactions.id'], ),
    sa.ForeignKeyConstraint(['tax_type_id'], ['tax_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ar_transaction_tax_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ar_transaction_id', sa.Integer(), nullable=True),
    sa.Column('tax_type_id', sa.Integer(), nullable=True),
    sa.Column('taxable_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('base_currency_tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['ar_transaction_id'], ['ar_transactions.id'], ),
    sa.ForeignKeyConstraint(['tax_type_id'], ['tax_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ap_transactions', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.add_column('ap_transactions', sa.Column('exchange_rate', sa.Numeric(precision=15, scale=6), nullable=True))
    op.add_column('ap_transactions', sa.Column('base_currency_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('ap_transactions', sa.Column('foreign_currency_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'ap_transactions', 'currencies', ['currency_id'], ['id'])
    op.add_column('ar_transactions', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.add_column('ar_transactions', sa.Column('exchange_rate', sa.Numeric(precision=15, scale=6), nullable=True))
    op.add_column('ar_transactions', sa.Column('base_currency_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('ar_transactions', sa.Column('foreign_currency_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'ar_transactions', 'currencies', ['currency_id'], ['id'])
    op.add_column('customers', sa.Column('default_currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'currencies', ['default_currency_id'], ['id'])
    op.add_column('gl_defaults', sa.Column('forex_gain_account_id', sa.Integer(), nullable=True))
    op.add_column('gl_defaults', sa.Column('forex_loss_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gl_defaults', 'gl_accounts', ['forex_loss_account_id'], ['id'])
    op.create_foreign_key(None, 'gl_defaults', 'gl_accounts', ['forex_gain_account_id'], ['id'])
    op.add_column('gl_journal_entry_lines', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.add_column('gl_journal_entry_lines', sa.Column('exchange_rate', sa.Numeric(precision=15, scale=6), nullable=True))
    op.add_column('gl_journal_entry_lines', sa.Column('foreign_currency_debit_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('gl_journal_entry_lines', sa.Column('foreign_currency_credit_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'gl_journal_entry_lines', 'currencies', ['currency_id'], ['id'])
    op.add_column('inventory_items', sa.Column('default_sales_tax_type_id', sa.Integer(), nullable=True))
    op.add_column('inventory_items', sa.Column('default_purchase_tax_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_items', 'tax_types', ['default_sales_tax_type_id'], ['id'])
    op.create_foreign_key(None, 'inventory_items', 'tax_types', ['default_purchase_tax_type_id'], ['id'])
    op.add_column('inventory_transactions', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('exchange_rate', sa.Numeric(precision=15, scale=6), nullable=True))
    op.add_column('inventory_transactions', sa.Column('base_currency_unit_cost', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('inventory_transactions', sa.Column('base_currency_total_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('inventory_transactions', sa.Column('foreign_currency_unit_cost', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('inventory_transactions', sa.Column('foreign_currency_total_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'inventory_transactions', 'currencies', ['currency_id'], ['id'])
    op.add_column('purchase_order_lines', sa.Column('base_currency_tax_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'purchase_order_lines', 'tax_types', ['tax_type_id'], ['id'])
    op.add_column('purchase_orders', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('exchange_rate', sa.Numeric(precision=15, scale=6), nullable=True))
    op.add_column('purchase_orders', sa.Column('base_currency_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('purchase_orders', sa.Column('foreign_currency_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'purchase_orders', 'currencies', ['currency_id'], ['id'])
    op.add_column('sales_order_lines', sa.Column('base_currency_tax_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'sales_order_lines', 'tax_types', ['tax_type_id'], ['id'])
    op.add_column('sales_orders', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.add_column('sales_orders', sa.Column('exchange_rate', sa.Numeric(precision=15, scale=6), nullable=True))
    op.add_column('sales_orders', sa.Column('base_currency_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('sales_orders', sa.Column('foreign_currency_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'sales_orders', 'currencies', ['currency_id'], ['id'])
    op.add_column('suppliers', sa.Column('default_currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'currencies', ['default_currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'default_currency_id')
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_column('sales_orders', 'foreign_currency_amount')
    op.drop_column('sales_orders', 'base_currency_amount')
    op.drop_column('sales_orders', 'exchange_rate')
    op.drop_column('sales_orders', 'currency_id')
    op.drop_constraint(None, 'sales_order_lines', type_='foreignkey')
    op.drop_column('sales_order_lines', 'base_currency_tax_amount')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'foreign_currency_amount')
    op.drop_column('purchase_orders', 'base_currency_amount')
    op.drop_column('purchase_orders', 'exchange_rate')
    op.drop_column('purchase_orders', 'currency_id')
    op.drop_constraint(None, 'purchase_order_lines', type_='foreignkey')
    op.drop_column('purchase_order_lines', 'base_currency_tax_amount')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_column('inventory_transactions', 'foreign_currency_total_value')
    op.drop_column('inventory_transactions', 'foreign_currency_unit_cost')
    op.drop_column('inventory_transactions', 'base_currency_total_value')
    op.drop_column('inventory_transactions', 'base_currency_unit_cost')
    op.drop_column('inventory_transactions', 'exchange_rate')
    op.drop_column('inventory_transactions', 'currency_id')
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'default_purchase_tax_type_id')
    op.drop_column('inventory_items', 'default_sales_tax_type_id')
    op.drop_constraint(None, 'gl_journal_entry_lines', type_='foreignkey')
    op.drop_column('gl_journal_entry_lines', 'foreign_currency_credit_amount')
    op.drop_column('gl_journal_entry_lines', 'foreign_currency_debit_amount')
    op.drop_column('gl_journal_entry_lines', 'exchange_rate')
    op.drop_column('gl_journal_entry_lines', 'currency_id')
    op.drop_constraint(None, 'gl_defaults', type_='foreignkey')
    op.drop_constraint(None, 'gl_defaults', type_='foreignkey')
    op.drop_column('gl_defaults', 'forex_loss_account_id')
    op.drop_column('gl_defaults', 'forex_gain_account_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'default_currency_id')
    op.drop_constraint(None, 'ar_transactions', type_='foreignkey')
    op.drop_column('ar_transactions', 'foreign_currency_amount')
    op.drop_column('ar_transactions', 'base_currency_amount')
    op.drop_column('ar_transactions', 'exchange_rate')
    op.drop_column('ar_transactions', 'currency_id')
    op.drop_constraint(None, 'ap_transactions', type_='foreignkey')
    op.drop_column('ap_transactions', 'foreign_currency_amount')
    op.drop_column('ap_transactions', 'base_currency_amount')
    op.drop_column('ap_transactions', 'exchange_rate')
    op.drop_column('ap_transactions', 'currency_id')
    op.drop_table('ar_transaction_tax_lines')
    op.drop_table('ap_transaction_tax_lines')
    op.drop_table('forex_gain_loss')
    op.drop_table('exchange_rate_history')
    # ### end Alembic commands ###
