"""Add POS models

Revision ID: cb8eefe9b000
Revises: 222b241a2d56
Create Date: 2025-06-29 01:57:20.497314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8eefe9b000'
down_revision: Union[str, None] = '222b241a2d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos_transaction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('base_type', sa.String(), nullable=False),
    sa.Column('affects_inventory', sa.Boolean(), nullable=True),
    sa.Column('affects_ar', sa.Boolean(), nullable=True),
    sa.Column('default_payment_method', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'company_id', name='uq_postranstype_name_company')
    )
    op.create_index(op.f('ix_pos_transaction_types_id'), 'pos_transaction_types', ['id'], unique=False)
    op.create_table('tills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('till_code', sa.String(), nullable=False),
    sa.Column('till_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('default_cashier_id', sa.Integer(), nullable=True),
    sa.Column('default_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('cash_gl_account_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cash_gl_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['default_cashier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['default_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('till_code', 'company_id', name='uq_till_code_company')
    )
    op.create_index(op.f('ix_tills_id'), 'tills', ['id'], unique=False)
    op.create_table('pos_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('default_customer_id', sa.Integer(), nullable=True),
    sa.Column('default_tax_type_id', sa.Integer(), nullable=True),
    sa.Column('receipt_header', sa.Text(), nullable=True),
    sa.Column('receipt_footer', sa.Text(), nullable=True),
    sa.Column('enable_negative_stock', sa.Boolean(), nullable=True),
    sa.Column('require_customer_for_credit', sa.Boolean(), nullable=True),
    sa.Column('auto_print_receipt', sa.Boolean(), nullable=True),
    sa.Column('default_sale_transaction_type_id', sa.Integer(), nullable=True),
    sa.Column('default_return_transaction_type_id', sa.Integer(), nullable=True),
    sa.Column('cash_rounding_method', sa.String(), nullable=True),
    sa.Column('next_transaction_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['default_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['default_return_transaction_type_id'], ['pos_transaction_types.id'], ),
    sa.ForeignKeyConstraint(['default_sale_transaction_type_id'], ['pos_transaction_types.id'], ),
    sa.ForeignKeyConstraint(['default_tax_type_id'], ['tax_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_index(op.f('ix_pos_defaults_id'), 'pos_defaults', ['id'], unique=False)
    op.create_table('pos_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('till_id', sa.Integer(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('opening_time', sa.DateTime(), nullable=False),
    sa.Column('closing_time', sa.DateTime(), nullable=True),
    sa.Column('opening_cash', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('closing_cash', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['till_id'], ['tills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_sessions_id'), 'pos_sessions', ['id'], unique=False)
    op.create_table('pos_cash_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('movement_datetime', sa.DateTime(), nullable=False),
    sa.Column('authorized_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authorized_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['pos_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_cash_movements_id'), 'pos_cash_movements', ['id'], unique=False)
    op.create_table('pos_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('transaction_number', sa.String(), nullable=False),
    sa.Column('transaction_datetime', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cash_tendered', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('change_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('linked_gl_journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('linked_ar_transaction_id', sa.Integer(), nullable=True),
    sa.Column('reference_transaction_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['linked_ar_transaction_id'], ['ar_transactions.id'], ),
    sa.ForeignKeyConstraint(['linked_gl_journal_entry_id'], ['gl_journal_entries.id'], ),
    sa.ForeignKeyConstraint(['reference_transaction_id'], ['pos_transactions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['pos_sessions.id'], ),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['pos_transaction_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_number', 'company_id', name='uq_postrans_number_company')
    )
    op.create_index(op.f('ix_pos_transactions_id'), 'pos_transactions', ['id'], unique=False)
    op.create_table('pos_transaction_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('barcode_used', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tax_type_id', sa.Integer(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['tax_type_id'], ['tax_types.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['pos_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_transaction_lines_id'), 'pos_transaction_lines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pos_transaction_lines_id'), table_name='pos_transaction_lines')
    op.drop_table('pos_transaction_lines')
    op.drop_index(op.f('ix_pos_transactions_id'), table_name='pos_transactions')
    op.drop_table('pos_transactions')
    op.drop_index(op.f('ix_pos_cash_movements_id'), table_name='pos_cash_movements')
    op.drop_table('pos_cash_movements')
    op.drop_index(op.f('ix_pos_sessions_id'), table_name='pos_sessions')
    op.drop_table('pos_sessions')
    op.drop_index(op.f('ix_pos_defaults_id'), table_name='pos_defaults')
    op.drop_table('pos_defaults')
    op.drop_index(op.f('ix_tills_id'), table_name='tills')
    op.drop_table('tills')
    op.drop_index(op.f('ix_pos_transaction_types_id'), table_name='pos_transaction_types')
    op.drop_table('pos_transaction_types')
    # ### end Alembic commands ###
