"""Add Inventory models

Revision ID: d2924ef62137
Revises: c8a2e6e7526d
Create Date: 2025-06-13 10:50:13.183688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2924ef62137'
down_revision: Union[str, None] = 'c8a2e6e7526d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_of_measures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('conversion_factor_to_base', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'company_id', name='uq_uom_name_company')
    )
    op.create_index(op.f('ix_unit_of_measures_id'), 'unit_of_measures', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'company_id', name='uq_warehouse_name_company')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('inventory_count_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('count_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_count_sessions_id'), 'inventory_count_sessions', ['id'], unique=False)
    op.create_table('inventory_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('default_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('default_inventory_gl_account_id', sa.Integer(), nullable=True),
    sa.Column('default_cogs_gl_account_id', sa.Integer(), nullable=True),
    sa.Column('default_sales_revenue_gl_account_id', sa.Integer(), nullable=True),
    sa.Column('default_inventory_adjustment_gl_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['default_cogs_gl_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['default_inventory_adjustment_gl_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['default_inventory_gl_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['default_sales_revenue_gl_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['default_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_index(op.f('ix_inventory_defaults_id'), 'inventory_defaults', ['id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=False),
    sa.Column('costing_method', sa.String(), nullable=True),
    sa.Column('standard_cost', sa.Numeric(), nullable=True),
    sa.Column('average_cost', sa.Numeric(), nullable=True),
    sa.Column('selling_price', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reorder_level', sa.Numeric(), nullable=True),
    sa.Column('reorder_quantity', sa.Numeric(), nullable=True),
    sa.Column('default_inventory_gl_account_id', sa.Integer(), nullable=True),
    sa.Column('default_cogs_gl_account_id', sa.Integer(), nullable=True),
    sa.Column('default_sales_gl_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['default_cogs_gl_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['default_inventory_gl_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['default_sales_gl_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_code', 'company_id', name='uq_inventoryitem_code_company')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_table('inventory_transaction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('base_type', sa.String(), nullable=False),
    sa.Column('affects_quantity_direction', sa.String(), nullable=False),
    sa.Column('default_offsetting_gl_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['default_offsetting_gl_account_id'], ['gl_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'company_id', name='uq_invtranstype_name_company')
    )
    op.create_index(op.f('ix_inventory_transaction_types_id'), 'inventory_transaction_types', ['id'], unique=False)
    op.create_table('inventory_count_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_count_session_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('system_quantity', sa.Numeric(), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(), nullable=True),
    sa.Column('variance_quantity', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_count_session_id'], ['inventory_count_sessions.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_count_lines_id'), 'inventory_count_lines', ['id'], unique=False)
    op.create_table('inventory_item_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(), nullable=True),
    sa.Column('quantity_committed', sa.Numeric(), nullable=True),
    sa.Column('quantity_on_order', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'warehouse_id', 'company_id', name='uq_item_warehouse_company')
    )
    op.create_index(op.f('ix_inventory_item_locations_id'), 'inventory_item_locations', ['id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('inventory_transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('linked_gl_journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(), nullable=False),
    sa.Column('total_value', sa.Numeric(), nullable=False),
    sa.Column('reference_document_type', sa.String(), nullable=True),
    sa.Column('reference_document_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['inventory_transaction_type_id'], ['inventory_transaction_types.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['linked_gl_journal_entry_id'], ['gl_journal_entries.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_table('item_barcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=True),
    sa.Column('quantity_in_uom', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode', 'company_id', name='uq_itembarcode_company')
    )
    op.create_index(op.f('ix_item_barcodes_id'), 'item_barcodes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_barcodes_id'), table_name='item_barcodes')
    op.drop_table('item_barcodes')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_inventory_item_locations_id'), table_name='inventory_item_locations')
    op.drop_table('inventory_item_locations')
    op.drop_index(op.f('ix_inventory_count_lines_id'), table_name='inventory_count_lines')
    op.drop_table('inventory_count_lines')
    op.drop_index(op.f('ix_inventory_transaction_types_id'), table_name='inventory_transaction_types')
    op.drop_table('inventory_transaction_types')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_inventory_defaults_id'), table_name='inventory_defaults')
    op.drop_table('inventory_defaults')
    op.drop_index(op.f('ix_inventory_count_sessions_id'), table_name='inventory_count_sessions')
    op.drop_table('inventory_count_sessions')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_unit_of_measures_id'), table_name='unit_of_measures')
    op.drop_table('unit_of_measures')
    # ### end Alembic commands ###
