"""add warehouse_code field to warehouses table

Revision ID: ec20384557f7
Revises: de03255fae9f
Create Date: 2025-07-25 12:01:11.522715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec20384557f7'
down_revision: Union[str, None] = 'de03255fae9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def table_exists(table_name: str) -> bool:
    """Check if a table exists in the database."""
    try:
        connection = op.get_bind()
        result = connection.execute(text(
            "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = :table_name)"
        ), {"table_name": table_name})
        return result.scalar()
    except Exception:
        return False
def index_exists(index_name: str) -> bool:
    """Check if an index exists in the database."""
    try:
        connection = op.get_bind()
        result = connection.execute(text(
            "SELECT EXISTS (SELECT FROM pg_indexes WHERE indexname = :index_name)"
        ), {"index_name": index_name})
        return result.scalar()
    except Exception:
        return False

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan_type', postgresql.ENUM('trial', 'basic', 'professional', 'enterprise', 'custom', name='billingplantype', create_type=False), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_transactions_per_month', sa.Integer(), nullable=True),
    sa.Column('max_storage_gb', sa.Integer(), nullable=True),
    sa.Column('max_api_calls_per_day', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    if not index_exists('ix_company_subscriptions_id'):

        op.create_index(op.f('ix_billing_plans_id'), 'billing_plans', ['id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_enabled_globally', sa.Boolean(), nullable=True),
    sa.Column('enabled_companies', sa.JSON(), nullable=True),
    sa.Column('disabled_companies', sa.JSON(), nullable=True),
    sa.Column('rollout_percentage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_id'), 'feature_flags', ['id'], unique=False)
    op.create_index(op.f('ix_feature_flags_name'), 'feature_flags', ['name'], unique=True)
    op.create_table('platform_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_admins_email'), 'platform_admins', ['email'], unique=True)
    op.create_index(op.f('ix_platform_admins_id'), 'platform_admins', ['id'], unique=False)
    op.create_table('system_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('memory_usage_mb', sa.Integer(), nullable=True),
    sa.Column('disk_usage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_health_checked_at'), 'system_health', ['checked_at'], unique=False)
    op.create_index(op.f('ix_system_health_id'), 'system_health', ['id'], unique=False)
    op.create_table('billing_configurations',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('billing_provider', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('payment_method_id', sa.String(), nullable=True),
    sa.Column('billing_cycle', sa.String(), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('custom_pricing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('billing_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('billing_period', sa.String(), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_billing_transaction_company', 'billing_transactions', ['company_id'], unique=False)
    op.create_index('idx_billing_transaction_stripe_invoice', 'billing_transactions', ['stripe_invoice_id'], unique=False)
    # Create company_subscriptions table only if it doesn't exist

    if not table_exists('company_subscriptions'):

        op.create_table('company_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('billing_plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('is_trial', sa.Boolean(), nullable=True),
    sa.Column('trial_end_date', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('billing_email', sa.String(), nullable=True),
    sa.Column('custom_limits', sa.JSON(), nullable=True),
    sa.Column('custom_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', postgresql.ENUM('trial', 'active', 'cancelled', 'expired', name='subscriptionstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_plan_id'], ['billing_plans.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_subscriptions_id'), 'company_subscriptions', ['id'], unique=False)
    op.create_table('resource_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('usage_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'resource_type', 'usage_date', name='uq_company_resource_date')
    )
    if not index_exists('ix_company_subscriptions_id'):

        op.create_index('idx_resource_usage_company_date', 'resource_usage', ['company_id', 'usage_date'], unique=False)
    op.create_table('system_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('requires_restart', sa.Boolean(), nullable=True),
    sa.Column('updated_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['platform_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configurations_id'), 'system_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_system_configurations_key'), 'system_configurations', ['key'], unique=True)
    op.create_table('usage_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', postgresql.ENUM('api_calls', 'storage', 'users', 'transactions', 'custom', name='usagemetrictype', create_type=False), nullable=False),
    sa.Column('metric_date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'metric_type', 'metric_date', name='uq_usage_metric_company_type_date')
    )
    op.create_index(op.f('ix_usage_metrics_created_at'), 'usage_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_metrics_id'), 'usage_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_usage_metrics_metric_date'), 'usage_metrics', ['metric_date'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('platform_admin_id', sa.Integer(), nullable=True),
    sa.Column('action', postgresql.ENUM('create', 'update', 'delete', 'login', 'logout', 'api_call', 'permission_change', 'subscription_change', 'other', name='auditactiontype', create_type=False), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('request_method', sa.String(), nullable=True),
    sa.Column('request_path', sa.String(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['platform_admin_id'], ['platform_admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_company_created', 'audit_logs', ['company_id', 'created_at'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('platform_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('usage_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['company_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_platform_invoices_id'), 'platform_invoices', ['id'], unique=False)
    op.create_table('usage_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('alert_date', sa.DateTime(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ap_trans_company_date', 'ap_transactions', ['company_id', 'transaction_date'], unique=False)
    op.create_index('idx_ap_trans_company_open', 'ap_transactions', ['company_id', 'open_amount'], unique=False)
    op.create_index('idx_ap_trans_company_supplier', 'ap_transactions', ['company_id', 'supplier_id'], unique=False)
    op.create_index('idx_ar_trans_company_customer', 'ar_transactions', ['company_id', 'customer_id'], unique=False)
    op.create_index('idx_ar_trans_company_date', 'ar_transactions', ['company_id', 'transaction_date'], unique=False)
    op.create_index('idx_ar_trans_company_open', 'ar_transactions', ['company_id', 'open_amount'], unique=False)
    op.alter_column('companies', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('companies', 'subscription_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'subscription_start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('companies', 'subscription_end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('companies', 'trial_end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('companies', 'storage_used_mb',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('companies', 'api_calls_this_month',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('companies', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('fk_companies_created_by_user_id'), 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=False)
    op.create_index('idx_customer_company_active', 'customers', ['company_id', 'is_active'], unique=False)
    op.create_index('idx_customer_company_balance', 'customers', ['company_id', 'current_balance'], unique=False)
    op.create_index(op.f('ix_gl_accounts_company_id'), 'gl_accounts', ['company_id'], unique=False)
    op.add_column('gl_journal_entries', sa.Column('posting_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('gl_journal_entries', sa.Column('approved_by_user_id', sa.Integer(), nullable=True))
    op.add_column('gl_journal_entries', sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('gl_journal_entries', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('gl_journal_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('gl_journal_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_gl_journal_entries_company_id'), 'gl_journal_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_gl_journal_entries_entry_date'), 'gl_journal_entries', ['entry_date'], unique=False)
    op.create_foreign_key(None, 'gl_journal_entries', 'users', ['approved_by_user_id'], ['id'])
    op.create_index('idx_gl_trans_type_company', 'gl_transaction_types', ['company_id'], unique=False)
    op.alter_column('goods_received_vouchers', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('ix_grv_company_date', 'goods_received_vouchers', ['company_id', 'grv_date'], unique=False)
    op.create_index('ix_grv_company_status', 'goods_received_vouchers', ['company_id', 'status'], unique=False)
    op.create_index('ix_grv_company_supplier', 'goods_received_vouchers', ['company_id', 'supplier_id'], unique=False)
    op.create_unique_constraint('uq_grv_doc_number_company', 'goods_received_vouchers', ['document_number', 'company_id'])
    op.alter_column('inventory_count_sessions', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('ix_count_session_company', 'inventory_count_sessions', ['company_id'], unique=False)
    op.create_index('ix_item_location_company', 'inventory_item_locations', ['company_id'], unique=False)
    op.create_index('ix_item_location_company_item', 'inventory_item_locations', ['company_id', 'item_id'], unique=False)
    op.drop_constraint(op.f('uq_inventoryitem_code_company'), 'inventory_items', type_='unique')
    op.create_index(op.f('ix_inventory_items_item_code'), 'inventory_items', ['item_code'], unique=False)
    op.create_index('ix_item_company_active', 'inventory_items', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_item_company_code', 'inventory_items', ['company_id', 'item_code'], unique=False)
    op.create_unique_constraint('uq_item_code_company', 'inventory_items', ['item_code', 'company_id'])
    op.drop_constraint(op.f('inventory_items_default_purchase_tax_type_id_fkey'), 'inventory_items', type_='foreignkey')
    op.drop_constraint(op.f('inventory_items_default_sales_tax_type_id_fkey'), 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'default_purchase_tax_type_id')
    op.drop_column('inventory_items', 'notes')
    op.drop_column('inventory_items', 'default_sales_tax_type_id')
    op.drop_column('inventory_items', 'reorder_quantity')
    op.drop_column('inventory_items', 'reorder_level')
    op.drop_constraint(op.f('uq_invtranstype_name_company'), 'inventory_transaction_types', type_='unique')
    op.create_index('ix_inv_trans_type_company', 'inventory_transaction_types', ['company_id'], unique=False)
    op.create_unique_constraint('uq_inv_trans_type_name_company', 'inventory_transaction_types', ['name', 'company_id'])
    op.alter_column('inventory_transactions', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('ix_inv_trans_company_date', 'inventory_transactions', ['company_id', 'transaction_date'], unique=False)
    op.create_index('ix_inv_trans_company_item', 'inventory_transactions', ['company_id', 'item_id'], unique=False)
    op.create_index('ix_inv_trans_company_warehouse', 'inventory_transactions', ['company_id', 'warehouse_id'], unique=False)
    op.drop_constraint(op.f('inventory_transactions_currency_id_fkey'), 'inventory_transactions', type_='foreignkey')
    op.drop_column('inventory_transactions', 'currency_id')
    op.drop_column('inventory_transactions', 'foreign_currency_unit_cost')
    op.drop_column('inventory_transactions', 'foreign_currency_total_value')
    op.drop_column('inventory_transactions', 'base_currency_total_value')
    op.drop_column('inventory_transactions', 'base_currency_unit_cost')
    op.drop_column('inventory_transactions', 'exchange_rate')
    op.drop_constraint(op.f('uq_itembarcode_company'), 'item_barcodes', type_='unique')
    op.create_index('ix_barcode_company', 'item_barcodes', ['company_id'], unique=False)
    op.create_unique_constraint('uq_barcode_company', 'item_barcodes', ['barcode', 'company_id'])
    op.alter_column('platform_audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('idx_platform_audit_company_timestamp', 'platform_audit_logs', ['company_id', 'timestamp'], unique=False)
    op.create_index('idx_platform_audit_user_timestamp', 'platform_audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_platform_audit_logs_action'), 'platform_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_platform_audit_logs_timestamp'), 'platform_audit_logs', ['timestamp'], unique=False)
    op.drop_column('purchase_order_lines', 'base_currency_tax_amount')
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('purchase_orders', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('ix_po_company_date', 'purchase_orders', ['company_id', 'order_date'], unique=False)
    op.create_index('ix_po_company_status', 'purchase_orders', ['company_id', 'status'], unique=False)
    op.create_index('ix_po_company_supplier', 'purchase_orders', ['company_id', 'supplier_id'], unique=False)
    op.create_unique_constraint('uq_po_doc_number_company', 'purchase_orders', ['document_number', 'company_id'])
    op.drop_constraint(op.f('purchase_orders_currency_id_fkey'), 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'currency_id')
    op.drop_column('purchase_orders', 'exchange_rate')
    op.drop_column('purchase_orders', 'base_currency_amount')
    op.drop_column('purchase_orders', 'foreign_currency_amount')
    op.drop_column('sales_order_lines', 'base_currency_tax_amount')
    op.alter_column('sales_orders', 'total_amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('sales_orders', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('ix_so_company_customer', 'sales_orders', ['company_id', 'customer_id'], unique=False)
    op.create_index('ix_so_company_date', 'sales_orders', ['company_id', 'order_date'], unique=False)
    op.create_index('ix_so_company_status', 'sales_orders', ['company_id', 'status'], unique=False)
    op.create_unique_constraint('uq_so_doc_number_company', 'sales_orders', ['document_number', 'company_id'])
    op.drop_constraint(op.f('sales_orders_currency_id_fkey'), 'sales_orders', type_='foreignkey')
    op.drop_column('sales_orders', 'currency_id')
    op.drop_column('sales_orders', 'exchange_rate')
    op.drop_column('sales_orders', 'base_currency_amount')
    op.drop_column('sales_orders', 'foreign_currency_amount')
    op.drop_index(op.f('ix_suppliers_supplier_code'), table_name='suppliers')
    op.create_index(op.f('ix_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=False)
    op.create_index('idx_supplier_company_active', 'suppliers', ['company_id', 'is_active'], unique=False)
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('warehouses', sa.Column('warehouse_code', sa.String(), nullable=False))
    op.create_index('ix_warehouse_company', 'warehouses', ['company_id'], unique=False)
    op.create_index('ix_warehouse_company_code', 'warehouses', ['company_id', 'warehouse_code'], unique=False)
    op.create_index(op.f('ix_warehouses_warehouse_code'), 'warehouses', ['warehouse_code'], unique=False)
    op.create_unique_constraint('uq_warehouse_code_company', 'warehouses', ['warehouse_code', 'company_id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_warehouse_code_company', 'warehouses', type_='unique')
    op.drop_index(op.f('ix_warehouses_warehouse_code'), table_name='warehouses')
    op.drop_index('ix_warehouse_company_code', table_name='warehouses')
    op.drop_index('ix_warehouse_company', table_name='warehouses')
    op.drop_column('warehouses', 'warehouse_code')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('idx_supplier_company_active', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_supplier_code'), table_name='suppliers')
    op.create_index(op.f('ix_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=True)
    op.add_column('sales_orders', sa.Column('foreign_currency_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('sales_orders', sa.Column('base_currency_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('sales_orders', sa.Column('exchange_rate', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True))
    op.add_column('sales_orders', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sales_orders_currency_id_fkey'), 'sales_orders', 'currencies', ['currency_id'], ['id'])
    op.drop_constraint('uq_so_doc_number_company', 'sales_orders', type_='unique')
    op.drop_index('ix_so_company_status', table_name='sales_orders')
    op.drop_index('ix_so_company_date', table_name='sales_orders')
    op.drop_index('ix_so_company_customer', table_name='sales_orders')
    op.alter_column('sales_orders', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sales_orders', 'total_amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.add_column('sales_order_lines', sa.Column('base_currency_tax_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('foreign_currency_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('base_currency_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('exchange_rate', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('purchase_orders_currency_id_fkey'), 'purchase_orders', 'currencies', ['currency_id'], ['id'])
    op.drop_constraint('uq_po_doc_number_company', 'purchase_orders', type_='unique')
    op.drop_index('ix_po_company_supplier', table_name='purchase_orders')
    op.drop_index('ix_po_company_status', table_name='purchase_orders')
    op.drop_index('ix_po_company_date', table_name='purchase_orders')
    op.alter_column('purchase_orders', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.add_column('purchase_order_lines', sa.Column('base_currency_tax_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_platform_audit_logs_timestamp'), table_name='platform_audit_logs')
    op.drop_index(op.f('ix_platform_audit_logs_action'), table_name='platform_audit_logs')
    op.drop_index('idx_platform_audit_user_timestamp', table_name='platform_audit_logs')
    op.drop_index('idx_platform_audit_company_timestamp', table_name='platform_audit_logs')
    op.alter_column('platform_audit_logs', 'user_agent',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint('uq_barcode_company', 'item_barcodes', type_='unique')
    op.drop_index('ix_barcode_company', table_name='item_barcodes')
    op.create_unique_constraint(op.f('uq_itembarcode_company'), 'item_barcodes', ['barcode', 'company_id'], postgresql_nulls_not_distinct=False)
    op.add_column('inventory_transactions', sa.Column('exchange_rate', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('base_currency_unit_cost', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('base_currency_total_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('foreign_currency_total_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('foreign_currency_unit_cost', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('inventory_transactions_currency_id_fkey'), 'inventory_transactions', 'currencies', ['currency_id'], ['id'])
    op.drop_index('ix_inv_trans_company_warehouse', table_name='inventory_transactions')
    op.drop_index('ix_inv_trans_company_item', table_name='inventory_transactions')
    op.drop_index('ix_inv_trans_company_date', table_name='inventory_transactions')
    op.alter_column('inventory_transactions', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_inv_trans_type_name_company', 'inventory_transaction_types', type_='unique')
    op.drop_index('ix_inv_trans_type_company', table_name='inventory_transaction_types')
    op.create_unique_constraint(op.f('uq_invtranstype_name_company'), 'inventory_transaction_types', ['name', 'company_id'], postgresql_nulls_not_distinct=False)
    op.add_column('inventory_items', sa.Column('reorder_level', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('inventory_items', sa.Column('reorder_quantity', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('inventory_items', sa.Column('default_sales_tax_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inventory_items', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('inventory_items', sa.Column('default_purchase_tax_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('inventory_items_default_sales_tax_type_id_fkey'), 'inventory_items', 'tax_types', ['default_sales_tax_type_id'], ['id'])
    op.create_foreign_key(op.f('inventory_items_default_purchase_tax_type_id_fkey'), 'inventory_items', 'tax_types', ['default_purchase_tax_type_id'], ['id'])
    op.drop_constraint('uq_item_code_company', 'inventory_items', type_='unique')
    op.drop_index('ix_item_company_code', table_name='inventory_items')
    op.drop_index('ix_item_company_active', table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_code'), table_name='inventory_items')
    op.create_unique_constraint(op.f('uq_inventoryitem_code_company'), 'inventory_items', ['item_code', 'company_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_item_location_company_item', table_name='inventory_item_locations')
    op.drop_index('ix_item_location_company', table_name='inventory_item_locations')
    op.drop_index('ix_count_session_company', table_name='inventory_count_sessions')
    op.alter_column('inventory_count_sessions', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_grv_doc_number_company', 'goods_received_vouchers', type_='unique')
    op.drop_index('ix_grv_company_supplier', table_name='goods_received_vouchers')
    op.drop_index('ix_grv_company_status', table_name='goods_received_vouchers')
    op.drop_index('ix_grv_company_date', table_name='goods_received_vouchers')
    op.alter_column('goods_received_vouchers', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('idx_gl_trans_type_company', table_name='gl_transaction_types')
    op.drop_constraint(None, 'gl_journal_entries', type_='foreignkey')
    op.drop_index(op.f('ix_gl_journal_entries_entry_date'), table_name='gl_journal_entries')
    op.drop_index(op.f('ix_gl_journal_entries_company_id'), table_name='gl_journal_entries')
    op.alter_column('gl_journal_entries', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('gl_journal_entries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('gl_journal_entries', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('gl_journal_entries', 'approval_date')
    op.drop_column('gl_journal_entries', 'approved_by_user_id')
    op.drop_column('gl_journal_entries', 'posting_date')
    op.drop_index(op.f('ix_gl_accounts_company_id'), table_name='gl_accounts')
    op.drop_index('idx_customer_company_balance', table_name='customers')
    op.drop_index('idx_customer_company_active', table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_foreign_key(op.f('fk_companies_created_by_user_id'), 'companies', 'users', ['created_by_user_id'], ['id'])
    op.alter_column('companies', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('companies', 'api_calls_this_month',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('companies', 'storage_used_mb',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('companies', 'trial_end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('companies', 'subscription_end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('companies', 'subscription_start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('companies', 'subscription_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index('idx_ar_trans_company_open', table_name='ar_transactions')
    op.drop_index('idx_ar_trans_company_date', table_name='ar_transactions')
    op.drop_index('idx_ar_trans_company_customer', table_name='ar_transactions')
    op.drop_index('idx_ap_trans_company_supplier', table_name='ap_transactions')
    op.drop_index('idx_ap_trans_company_open', table_name='ap_transactions')
    op.drop_index('idx_ap_trans_company_date', table_name='ap_transactions')
    op.drop_table('usage_alerts')
    op.drop_index(op.f('ix_platform_invoices_id'), table_name='platform_invoices')
    op.drop_table('platform_invoices')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_created', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_company_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_usage_metrics_metric_date'), table_name='usage_metrics')
    op.drop_index(op.f('ix_usage_metrics_id'), table_name='usage_metrics')
    op.drop_index(op.f('ix_usage_metrics_created_at'), table_name='usage_metrics')
    op.drop_table('usage_metrics')
    op.drop_index(op.f('ix_system_configurations_key'), table_name='system_configurations')
    op.drop_index(op.f('ix_system_configurations_id'), table_name='system_configurations')
    op.drop_table('system_configurations')
    op.drop_index('idx_resource_usage_company_date', table_name='resource_usage')
    op.drop_table('resource_usage')
    op.drop_index(op.f('ix_company_subscriptions_id'), table_name='company_subscriptions')
    op.drop_table('company_subscriptions')
    op.drop_index('idx_billing_transaction_stripe_invoice', table_name='billing_transactions')
    op.drop_index('idx_billing_transaction_company', table_name='billing_transactions')
    op.drop_table('billing_transactions')
    op.drop_table('billing_configurations')
    op.drop_index(op.f('ix_system_health_id'), table_name='system_health')
    op.drop_index(op.f('ix_system_health_checked_at'), table_name='system_health')
    op.drop_table('system_health')
    op.drop_index(op.f('ix_platform_admins_id'), table_name='platform_admins')
    op.drop_index(op.f('ix_platform_admins_email'), table_name='platform_admins')
    op.drop_table('platform_admins')
    op.drop_index(op.f('ix_feature_flags_name'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_id'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_billing_plans_id'), table_name='billing_plans')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###
