"""New migration

Revision ID: f35b1fc66465
Revises: 1be7468c7e9d
Create Date: 2025-08-04 14:17:17.521657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f35b1fc66465'
down_revision: Union[str, None] = '1be7468c7e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def table_exists(table_name: str) -> bool:
    """Check if a table exists in the database."""
    try:
        connection = op.get_bind()
        result = connection.execute(text(
            "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = :table_name)"
        ), {"table_name": table_name})
        return result.scalar()
    except Exception:
        return False

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan_type', sa.Enum('trial', 'basic', 'professional', 'enterprise', 'custom', name='billingplantype', create_type=False), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_transactions_per_month', sa.Integer(), nullable=True),
    sa.Column('max_storage_gb', sa.Integer(), nullable=True),
    sa.Column('max_api_calls_per_day', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_billing_plans_id'), 'billing_plans', ['id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_enabled_globally', sa.Boolean(), nullable=True),
    sa.Column('enabled_companies', sa.JSON(), nullable=True),
    sa.Column('disabled_companies', sa.JSON(), nullable=True),
    sa.Column('rollout_percentage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_id'), 'feature_flags', ['id'], unique=False)
    op.create_index(op.f('ix_feature_flags_name'), 'feature_flags', ['name'], unique=True)
    op.create_table('material_requisitions_placeholder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturing_order_id', sa.Integer(), nullable=False),
    sa.Column('component_item_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('issued_quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_requisitions_placeholder_id'), 'material_requisitions_placeholder', ['id'], unique=False)
    op.create_table('platform_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_admins_email'), 'platform_admins', ['email'], unique=True)
    op.create_index(op.f('ix_platform_admins_id'), 'platform_admins', ['id'], unique=False)
    op.create_table('production_entries_placeholder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturing_order_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('quantity_produced', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('quantity_scrapped', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('labor_hours_actual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('linked_gl_journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_entries_placeholder_id'), 'production_entries_placeholder', ['id'], unique=False)
    op.create_table('system_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('memory_usage_mb', sa.Integer(), nullable=True),
    sa.Column('disk_usage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_health_checked_at'), 'system_health', ['checked_at'], unique=False)
    op.create_index(op.f('ix_system_health_id'), 'system_health', ['id'], unique=False)
    # Create company_subscriptions table only if it doesn't exist

    if not table_exists('company_subscriptions'):

        op.create_table('company_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('billing_plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('is_trial', sa.Boolean(), nullable=True),
    sa.Column('trial_end_date', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('billing_email', sa.String(), nullable=True),
    sa.Column('custom_limits', sa.JSON(), nullable=True),
    sa.Column('custom_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('trial', 'active', 'cancelled', 'expired', name='subscriptionstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_plan_id'], ['billing_plans.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_subscriptions_id'), 'company_subscriptions', ['id'], unique=False)
    op.create_table('feedback_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_category_company', 'feedback_categories', ['company_id'], unique=False)
    op.create_index(op.f('ix_feedback_categories_id'), 'feedback_categories', ['id'], unique=False)
    op.create_table('financial_reporting_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=True),
    sa.Column('period_name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('closing_entries_posted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_reporting_periods_id'), 'financial_reporting_periods', ['id'], unique=False)
    op.create_table('system_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('requires_restart', sa.Boolean(), nullable=True),
    sa.Column('updated_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['platform_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configurations_id'), 'system_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_system_configurations_key'), 'system_configurations', ['key'], unique=True)
    op.create_table('usage_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.Enum('API_CALLS', 'STORAGE', 'USERS', 'TRANSACTIONS', 'CUSTOM', name='usagemetrictype'), nullable=False),
    sa.Column('metric_date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'metric_type', 'metric_date', name='uq_usage_metric_company_type_date')
    )
    op.create_index(op.f('ix_usage_metrics_created_at'), 'usage_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_metrics_id'), 'usage_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_usage_metrics_metric_date'), 'usage_metrics', ['metric_date'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('platform_admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'API_CALL', 'PERMISSION_CHANGE', 'SUBSCRIPTION_CHANGE', 'OTHER', name='auditactiontype'), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('request_method', sa.String(), nullable=True),
    sa.Column('request_path', sa.String(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['platform_admin_id'], ['platform_admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_company_created', 'audit_logs', ['company_id', 'created_at'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('feedback_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('actual_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_assigned', 'feedback_requests', ['assigned_to_user_id'], unique=False)
    op.create_index('ix_feedback_company_module', 'feedback_requests', ['company_id', 'module'], unique=False)
    op.create_index('ix_feedback_company_status', 'feedback_requests', ['company_id', 'status'], unique=False)
    op.create_index('ix_feedback_company_type', 'feedback_requests', ['company_id', 'request_type'], unique=False)
    op.create_index(op.f('ix_feedback_requests_id'), 'feedback_requests', ['id'], unique=False)
    op.create_index('ix_feedback_user', 'feedback_requests', ['user_id'], unique=False)
    op.create_table('platform_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('usage_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['company_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_platform_invoices_id'), 'platform_invoices', ['id'], unique=False)
    op.create_table('feedback_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_request_id'], ['feedback_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comment_request', 'feedback_comments', ['feedback_request_id'], unique=False)
    op.create_index('ix_comment_user', 'feedback_comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_feedback_comments_id'), 'feedback_comments', ['id'], unique=False)
    op.create_table('generated_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.Enum('BALANCE_SHEET', 'INCOME_STATEMENT', 'CASH_FLOW', 'TRIAL_BALANCE', 'CUSTOM', 'AR_AGING', 'AP_AGING', 'INVENTORY_VALUATION', name='reporttype'), nullable=False),
    sa.Column('report_name', sa.String(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_reports_id'), 'generated_reports', ['id'], unique=False)
    op.create_table('pos_tills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('till_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('hardware_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('default_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('default_customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['default_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['default_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('till_number', 'company_id', name='uq_till_number_company')
    )
    op.create_index(op.f('ix_pos_tills_id'), 'pos_tills', ['id'], unique=False)
    op.create_table('pos_till_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('till_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opening_date', sa.DateTime(), nullable=False),
    sa.Column('closing_date', sa.DateTime(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('expected_closing_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_closing_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reconciliation_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['till_id'], ['pos_tills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_till_sessions_id'), 'pos_till_sessions', ['id'], unique=False)
    op.create_table('till_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('actual_cash', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('variance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reconciliation_time', sa.DateTime(), nullable=False),
    sa.Column('reconciled_by_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['reconciled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['pos_till_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_till_reconciliations_id'), 'till_reconciliations', ['id'], unique=False)
    op.create_table('pos_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('payment_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['pos_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_payments_id'), 'pos_payments', ['id'], unique=False)
    op.drop_index(op.f('ix_pos_sessions_id'), table_name='pos_sessions')
    op.drop_table('pos_sessions')
    op.drop_index(op.f('ix_tills_id'), table_name='tills')
    op.drop_table('tills')
    op.create_index('idx_ap_trans_company_date', 'ap_transactions', ['company_id', 'transaction_date'], unique=False)
    op.create_index('idx_ap_trans_company_open', 'ap_transactions', ['company_id', 'open_amount'], unique=False)
    op.create_index('idx_ap_trans_company_supplier', 'ap_transactions', ['company_id', 'supplier_id'], unique=False)
    op.add_column('ar_defaults', sa.Column('default_payment_terms', sa.String(length=100), nullable=True))
    op.add_column('ar_defaults', sa.Column('default_credit_limit', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_index('idx_ar_trans_company_customer', 'ar_transactions', ['company_id', 'customer_id'], unique=False)
    op.create_index('idx_ar_trans_company_date', 'ar_transactions', ['company_id', 'transaction_date'], unique=False)
    op.create_index('idx_ar_trans_company_open', 'ar_transactions', ['company_id', 'open_amount'], unique=False)
    op.add_column('billing_configurations', sa.Column('billing_provider', sa.String(), nullable=True))
    op.add_column('billing_configurations', sa.Column('customer_id', sa.String(), nullable=True))
    op.add_column('billing_configurations', sa.Column('subscription_id', sa.String(), nullable=True))
    op.add_column('billing_configurations', sa.Column('payment_method_id', sa.String(), nullable=True))
    op.add_column('billing_configurations', sa.Column('next_billing_date', sa.Date(), nullable=True))
    op.add_column('billing_configurations', sa.Column('custom_pricing', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('billing_configurations', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_constraint(op.f('uq_billing_config_company'), 'billing_configurations', type_='unique')
    op.drop_column('billing_configurations', 'updated_at')
    op.drop_column('billing_configurations', 'id')
    op.drop_column('billing_configurations', 'per_user_fee')
    op.drop_column('billing_configurations', 'base_monthly_fee')
    op.drop_column('billing_configurations', 'per_gb_storage_fee')
    op.drop_column('billing_configurations', 'billing_email')
    op.drop_column('billing_configurations', 'stripe_customer_id')
    op.drop_column('billing_configurations', 'created_at')
    op.drop_column('billing_configurations', 'stripe_subscription_id')
    op.drop_column('billing_configurations', 'per_transaction_fee')
    op.drop_column('billing_configurations', 'payment_method')
    op.alter_column('billing_transactions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('billing_transactions', 'billing_period',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('billing_transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('idx_billing_transaction_company_period'), table_name='billing_transactions')
    op.create_index('idx_billing_transaction_company', 'billing_transactions', ['company_id'], unique=False)
    op.create_index('idx_billing_transaction_stripe_invoice', 'billing_transactions', ['stripe_invoice_id'], unique=False)
    op.drop_column('billing_transactions', 'stripe_charge_id')
    op.alter_column('bom_components', 'unit_of_measure_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bom_components', 'sequence_number')
    op.add_column('bom_defaults', sa.Column('default_overhead_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('bom_defaults', sa.Column('default_labor_rate_per_hour', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bom_defaults', sa.Column('wip_gl_account_id', sa.Integer(), nullable=True))
    op.add_column('bom_defaults', sa.Column('labor_gl_account_id', sa.Integer(), nullable=True))
    op.add_column('bom_defaults', sa.Column('overhead_gl_account_id', sa.Integer(), nullable=True))
    op.add_column('bom_defaults', sa.Column('variance_gl_account_id', sa.Integer(), nullable=True))
    op.add_column('bom_defaults', sa.Column('auto_issue_components', sa.Boolean(), nullable=True))
    op.add_column('bom_defaults', sa.Column('allow_negative_inventory', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('bom_defaults_default_manufacturing_overhead_gl_account_id_fkey'), 'bom_defaults', type_='foreignkey')
    op.drop_constraint(op.f('bom_defaults_default_material_usage_gl_account_id_fkey'), 'bom_defaults', type_='foreignkey')
    op.drop_constraint(op.f('bom_defaults_default_wip_gl_account_id_fkey'), 'bom_defaults', type_='foreignkey')
    op.drop_constraint(op.f('bom_defaults_default_scrap_gl_account_id_fkey'), 'bom_defaults', type_='foreignkey')
    op.create_foreign_key(None, 'bom_defaults', 'gl_accounts', ['overhead_gl_account_id'], ['id'])
    op.create_foreign_key(None, 'bom_defaults', 'gl_accounts', ['variance_gl_account_id'], ['id'])
    op.create_foreign_key(None, 'bom_defaults', 'gl_accounts', ['wip_gl_account_id'], ['id'])
    op.create_foreign_key(None, 'bom_defaults', 'gl_accounts', ['labor_gl_account_id'], ['id'])
    op.drop_column('bom_defaults', 'next_mo_number')
    op.drop_column('bom_defaults', 'default_wip_gl_account_id')
    op.drop_column('bom_defaults', 'default_manufacturing_overhead_gl_account_id')
    op.drop_column('bom_defaults', 'default_material_usage_gl_account_id')
    op.drop_column('bom_defaults', 'default_scrap_gl_account_id')
    op.drop_index(op.f('idx_company_code'), table_name='companies')
    op.drop_constraint(op.f('fk_companies_created_by_user'), 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=False)
    op.create_index('idx_customer_company_active', 'customers', ['company_id', 'is_active'], unique=False)
    op.create_index('idx_customer_company_balance', 'customers', ['company_id', 'current_balance'], unique=False)
    op.add_column('gl_accounts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('gl_accounts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_gl_accounts_company_id'), 'gl_accounts', ['company_id'], unique=False)
    op.add_column('gl_journal_entries', sa.Column('transaction_type_id', sa.Integer(), nullable=True))
    op.add_column('gl_journal_entries', sa.Column('posting_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('gl_journal_entries', sa.Column('approved_by_user_id', sa.Integer(), nullable=True))
    op.add_column('gl_journal_entries', sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('gl_journal_entries', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('gl_journal_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('gl_journal_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_gl_journal_entries_company_id'), 'gl_journal_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_gl_journal_entries_entry_date'), 'gl_journal_entries', ['entry_date'], unique=False)
    op.create_foreign_key(None, 'gl_journal_entries', 'gl_transaction_types', ['transaction_type_id'], ['id'])
    op.create_foreign_key(None, 'gl_journal_entries', 'users', ['approved_by_user_id'], ['id'])
    op.add_column('gl_journal_entry_lines', sa.Column('is_tax_line', sa.Boolean(), nullable=True))
    op.add_column('gl_journal_entry_lines', sa.Column('tax_base_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('gl_transaction_types', sa.Column('default_tax_control_account_id', sa.Integer(), nullable=True))
    op.add_column('gl_transaction_types', sa.Column('is_tax_applicable', sa.Boolean(), nullable=True))
    op.add_column('gl_transaction_types', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('gl_transaction_types', sa.Column('tax_calculation_method', sa.Enum('NONE', 'INCLUSIVE', 'EXCLUSIVE', name='taxcalculationmethod'), nullable=True))
    op.add_column('gl_transaction_types', sa.Column('tax_type_id', sa.Integer(), nullable=True))
    op.create_index('idx_gl_trans_type_company', 'gl_transaction_types', ['company_id'], unique=False)
    op.create_index(op.f('ix_gl_transaction_types_name'), 'gl_transaction_types', ['name'], unique=False)
    op.create_foreign_key(None, 'gl_transaction_types', 'tax_types', ['tax_type_id'], ['id'])
    op.create_foreign_key(None, 'gl_transaction_types', 'gl_accounts', ['default_tax_control_account_id'], ['id'])
    op.alter_column('goods_received_vouchers', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('ix_grv_company_date', 'goods_received_vouchers', ['company_id', 'grv_date'], unique=False)
    op.create_index('ix_grv_company_status', 'goods_received_vouchers', ['company_id', 'status'], unique=False)
    op.create_index('ix_grv_company_supplier', 'goods_received_vouchers', ['company_id', 'supplier_id'], unique=False)
    op.create_unique_constraint('uq_grv_doc_number_company', 'goods_received_vouchers', ['document_number', 'company_id'])
    op.alter_column('inventory_count_sessions', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('ix_count_session_company', 'inventory_count_sessions', ['company_id'], unique=False)
    op.add_column('inventory_defaults', sa.Column('default_grv_clearing_gl_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_defaults', 'gl_accounts', ['default_grv_clearing_gl_account_id'], ['id'])
    op.create_index('ix_item_location_company', 'inventory_item_locations', ['company_id'], unique=False)
    op.create_index('ix_item_location_company_item', 'inventory_item_locations', ['company_id', 'item_id'], unique=False)
    op.drop_constraint(op.f('uq_inventoryitem_code_company'), 'inventory_items', type_='unique')
    op.create_index(op.f('ix_inventory_items_item_code'), 'inventory_items', ['item_code'], unique=False)
    op.create_index('ix_item_company_active', 'inventory_items', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_item_company_code', 'inventory_items', ['company_id', 'item_code'], unique=False)
    op.create_unique_constraint('uq_item_code_company', 'inventory_items', ['item_code', 'company_id'])
    op.drop_constraint(op.f('inventory_items_default_sales_tax_type_id_fkey'), 'inventory_items', type_='foreignkey')
    op.drop_constraint(op.f('inventory_items_default_purchase_tax_type_id_fkey'), 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'default_sales_tax_type_id')
    op.drop_column('inventory_items', 'default_purchase_tax_type_id')
    op.drop_constraint(op.f('uq_invtranstype_name_company'), 'inventory_transaction_types', type_='unique')
    op.create_index('ix_inv_trans_type_company', 'inventory_transaction_types', ['company_id'], unique=False)
    op.create_unique_constraint('uq_inv_trans_type_name_company', 'inventory_transaction_types', ['name', 'company_id'])
    op.alter_column('inventory_transactions', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('ix_inv_trans_company_date', 'inventory_transactions', ['company_id', 'transaction_date'], unique=False)
    op.create_index('ix_inv_trans_company_item', 'inventory_transactions', ['company_id', 'item_id'], unique=False)
    op.create_index('ix_inv_trans_company_warehouse', 'inventory_transactions', ['company_id', 'warehouse_id'], unique=False)
    op.drop_constraint(op.f('inventory_transactions_currency_id_fkey'), 'inventory_transactions', type_='foreignkey')
    op.drop_column('inventory_transactions', 'base_currency_total_value')
    op.drop_column('inventory_transactions', 'base_currency_unit_cost')
    op.drop_column('inventory_transactions', 'currency_id')
    op.drop_column('inventory_transactions', 'exchange_rate')
    op.drop_column('inventory_transactions', 'foreign_currency_unit_cost')
    op.drop_column('inventory_transactions', 'foreign_currency_total_value')
    op.drop_constraint(op.f('uq_itembarcode_company'), 'item_barcodes', type_='unique')
    op.create_index('ix_barcode_company', 'item_barcodes', ['company_id'], unique=False)
    op.create_unique_constraint('uq_barcode_company', 'item_barcodes', ['barcode', 'company_id'])
    op.alter_column('manufacturing_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('order_defaults', sa.Column('default_currency_code', sa.String(), nullable=True))
    op.add_column('order_defaults', sa.Column('default_payment_terms', sa.String(), nullable=True))
    op.add_column('order_defaults', sa.Column('default_sales_representative_id', sa.Integer(), nullable=True))
    op.add_column('order_defaults', sa.Column('default_warehouse_id', sa.Integer(), nullable=True))
    op.add_column('order_defaults', sa.Column('auto_generate_order_numbers', sa.Boolean(), nullable=True))
    op.add_column('order_defaults', sa.Column('sales_order_number_prefix', sa.String(), nullable=True))
    op.add_column('order_defaults', sa.Column('purchase_order_number_prefix', sa.String(), nullable=True))
    op.add_column('order_defaults', sa.Column('grv_number_prefix', sa.String(), nullable=True))
    op.add_column('order_defaults', sa.Column('require_approval_for_orders', sa.Boolean(), nullable=True))
    op.add_column('order_defaults', sa.Column('order_approval_limit', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'order_defaults', 'sales_representatives', ['default_sales_representative_id'], ['id'])
    op.create_foreign_key(None, 'order_defaults', 'warehouses', ['default_warehouse_id'], ['id'])
    op.alter_column('platform_audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_platform_audit_logs_company_id'), table_name='platform_audit_logs')
    op.drop_index(op.f('idx_platform_audit_logs_timestamp'), table_name='platform_audit_logs')
    op.drop_index(op.f('idx_platform_audit_logs_user_id'), table_name='platform_audit_logs')
    op.create_index('idx_platform_audit_company_timestamp', 'platform_audit_logs', ['company_id', 'timestamp'], unique=False)
    op.create_index('idx_platform_audit_user_timestamp', 'platform_audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_platform_audit_logs_action'), 'platform_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_platform_audit_logs_timestamp'), 'platform_audit_logs', ['timestamp'], unique=False)
    op.drop_constraint(op.f('pos_cash_movements_session_id_fkey'), 'pos_cash_movements', type_='foreignkey')
    op.create_foreign_key(None, 'pos_cash_movements', 'pos_till_sessions', ['session_id'], ['id'])
    op.add_column('pos_defaults', sa.Column('default_walk_in_customer_id', sa.Integer(), nullable=True))
    op.add_column('pos_defaults', sa.Column('allow_negative_stock', sa.Boolean(), nullable=True))
    op.add_column('pos_defaults', sa.Column('cash_rounding_precision', sa.Numeric(precision=3, scale=2), nullable=True))
    op.drop_index(op.f('ix_pos_defaults_id'), table_name='pos_defaults')
    op.drop_constraint(op.f('pos_defaults_default_customer_id_fkey'), 'pos_defaults', type_='foreignkey')
    op.drop_constraint(op.f('pos_defaults_default_return_transaction_type_id_fkey'), 'pos_defaults', type_='foreignkey')
    op.drop_constraint(op.f('pos_defaults_default_sale_transaction_type_id_fkey'), 'pos_defaults', type_='foreignkey')
    op.create_foreign_key(None, 'pos_defaults', 'customers', ['default_walk_in_customer_id'], ['id'])
    op.drop_column('pos_defaults', 'next_transaction_number')
    op.drop_column('pos_defaults', 'default_customer_id')
    op.drop_column('pos_defaults', 'default_return_transaction_type_id')
    op.drop_column('pos_defaults', 'enable_negative_stock')
    op.drop_column('pos_defaults', 'default_sale_transaction_type_id')
    op.alter_column('pos_transaction_lines', 'quantity',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('pos_transaction_lines', 'barcode_used')
    op.add_column('pos_transaction_types', sa.Column('gl_account_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_postranstype_name_company'), 'pos_transaction_types', type_='unique')
    op.create_unique_constraint('uq_pos_trans_type_company', 'pos_transaction_types', ['name', 'company_id'])
    op.create_foreign_key(None, 'pos_transaction_types', 'gl_accounts', ['gl_account_id'], ['id'])
    op.drop_column('pos_transaction_types', 'description')
    op.drop_column('pos_transaction_types', 'affects_ar')
    op.drop_column('pos_transaction_types', 'affects_inventory')
    op.add_column('pos_transactions', sa.Column('till_session_id', sa.Integer(), nullable=False))
    op.add_column('pos_transactions', sa.Column('transaction_date', sa.DateTime(), nullable=False))
    op.add_column('pos_transactions', sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('pos_transactions', sa.Column('payment_details', sa.JSON(), nullable=True))
    op.add_column('pos_transactions', sa.Column('receipt_printed', sa.Boolean(), nullable=True))
    op.add_column('pos_transactions', sa.Column('receipt_email_sent', sa.Boolean(), nullable=True))
    op.alter_column('pos_transactions', 'tax_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('pos_transactions', 'discount_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('pos_transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('uq_postrans_number_company'), 'pos_transactions', type_='unique')
    op.create_unique_constraint(None, 'pos_transactions', ['transaction_number'])
    op.drop_constraint(op.f('pos_transactions_session_id_fkey'), 'pos_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'pos_transactions', 'pos_till_sessions', ['till_session_id'], ['id'])
    op.drop_column('pos_transactions', 'cash_tendered')
    op.drop_column('pos_transactions', 'transaction_datetime')
    op.drop_column('pos_transactions', 'session_id')
    op.drop_column('pos_transactions', 'subtotal_amount')
    op.drop_column('pos_transactions', 'notes')
    op.drop_column('pos_transactions', 'change_amount')
    op.drop_column('purchase_order_lines', 'base_currency_tax_amount')
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('purchase_orders', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('ix_po_company_date', 'purchase_orders', ['company_id', 'order_date'], unique=False)
    op.create_index('ix_po_company_status', 'purchase_orders', ['company_id', 'status'], unique=False)
    op.create_index('ix_po_company_supplier', 'purchase_orders', ['company_id', 'supplier_id'], unique=False)
    op.create_unique_constraint('uq_po_doc_number_company', 'purchase_orders', ['document_number', 'company_id'])
    op.drop_constraint(op.f('purchase_orders_currency_id_fkey'), 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'exchange_rate')
    op.drop_column('purchase_orders', 'base_currency_amount')
    op.drop_column('purchase_orders', 'currency_id')
    op.drop_column('purchase_orders', 'foreign_currency_amount')
    op.add_column('report_schedules', sa.Column('template_id', sa.Integer(), nullable=False))
    op.add_column('report_schedules', sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'ON_DEMAND', name='reportfrequency'), nullable=False))
    op.add_column('report_schedules', sa.Column('schedule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('report_schedules', sa.Column('recipient_emails', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('report_schedules', sa.Column('export_formats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('report_schedules', sa.Column('last_run_at', sa.DateTime(), nullable=True))
    op.add_column('report_schedules', sa.Column('next_run_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('report_schedules_report_template_id_fkey'), 'report_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'report_schedules', 'report_templates', ['template_id'], ['id'])
    op.drop_column('report_schedules', 'next_run_date')
    op.drop_column('report_schedules', 'name')
    op.drop_column('report_schedules', 'schedule_frequency')
    op.drop_column('report_schedules', 'schedule_parameters')
    op.drop_column('report_schedules', 'report_template_id')
    op.drop_column('report_schedules', 'last_run_date')
    op.add_column('report_templates', sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('report_templates', sa.Column('is_system', sa.Boolean(), nullable=True))
    op.alter_column('report_templates', 'report_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('BALANCE_SHEET', 'INCOME_STATEMENT', 'CASH_FLOW', 'TRIAL_BALANCE', 'CUSTOM', 'AR_AGING', 'AP_AGING', 'INVENTORY_VALUATION', name='reporttype'),
               existing_nullable=False)
    op.alter_column('report_templates', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('report_templates', 'is_default')
    op.drop_column('report_templates', 'template_data')
    op.add_column('resource_usage', sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False))
    op.add_column('resource_usage', sa.Column('unit', sa.String(), nullable=False))
    op.add_column('resource_usage', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_resource_usage_billing_period'), table_name='resource_usage')
    op.drop_constraint(op.f('uq_usage_company_resource_date'), 'resource_usage', type_='unique')
    op.create_unique_constraint('uq_company_resource_date', 'resource_usage', ['company_id', 'resource_type', 'usage_date'])
    op.drop_column('resource_usage', 'billing_period')
    op.drop_column('resource_usage', 'usage_amount')
    op.drop_column('sales_order_lines', 'base_currency_tax_amount')
    op.alter_column('sales_orders', 'total_amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('sales_orders', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('ix_so_company_customer', 'sales_orders', ['company_id', 'customer_id'], unique=False)
    op.create_index('ix_so_company_date', 'sales_orders', ['company_id', 'order_date'], unique=False)
    op.create_index('ix_so_company_status', 'sales_orders', ['company_id', 'status'], unique=False)
    op.create_unique_constraint('uq_so_doc_number_company', 'sales_orders', ['document_number', 'company_id'])
    op.drop_constraint(op.f('sales_orders_currency_id_fkey'), 'sales_orders', type_='foreignkey')
    op.drop_column('sales_orders', 'exchange_rate')
    op.drop_column('sales_orders', 'base_currency_amount')
    op.drop_column('sales_orders', 'currency_id')
    op.drop_column('sales_orders', 'foreign_currency_amount')
    op.drop_index(op.f('ix_suppliers_supplier_code'), table_name='suppliers')
    op.create_index(op.f('ix_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=False)
    op.create_index('idx_supplier_company_active', 'suppliers', ['company_id', 'is_active'], unique=False)
    op.add_column('unit_of_measures', sa.Column('is_base_unit', sa.Boolean(), nullable=False))
    op.create_index('ix_company_base_unit', 'unit_of_measures', ['company_id', 'is_base_unit'], unique=True, postgresql_where=sa.text('is_base_unit'))
    op.create_index('ix_uom_company', 'unit_of_measures', ['company_id'], unique=False)
    op.create_unique_constraint('uq_uom_abbrev_company', 'unit_of_measures', ['abbreviation', 'company_id'])
    op.add_column('usage_alerts', sa.Column('threshold_value', sa.Numeric(precision=15, scale=4), nullable=False))
    op.add_column('usage_alerts', sa.Column('current_value', sa.Numeric(precision=15, scale=4), nullable=False))
    op.add_column('usage_alerts', sa.Column('alert_date', sa.DateTime(), nullable=True))
    op.add_column('usage_alerts', sa.Column('acknowledged', sa.Boolean(), nullable=True))
    op.add_column('usage_alerts', sa.Column('acknowledged_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usage_alerts', 'users', ['acknowledged_by'], ['id'])
    op.drop_column('usage_alerts', 'threshold_percentage')
    op.drop_column('usage_alerts', 'alert_recipients')
    op.drop_column('usage_alerts', 'last_triggered')
    op.drop_column('usage_alerts', 'is_active')
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('warehouses', sa.Column('warehouse_code', sa.String(), nullable=False))
    op.create_index('ix_warehouse_company', 'warehouses', ['company_id'], unique=False)
    op.create_index('ix_warehouse_company_code', 'warehouses', ['company_id', 'warehouse_code'], unique=False)
    op.create_index(op.f('ix_warehouses_warehouse_code'), 'warehouses', ['warehouse_code'], unique=False)
    op.create_unique_constraint('uq_warehouse_code_company', 'warehouses', ['warehouse_code', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_warehouse_code_company', 'warehouses', type_='unique')
    op.drop_index(op.f('ix_warehouses_warehouse_code'), table_name='warehouses')
    op.drop_index('ix_warehouse_company_code', table_name='warehouses')
    op.drop_index('ix_warehouse_company', table_name='warehouses')
    op.drop_column('warehouses', 'warehouse_code')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('usage_alerts', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('usage_alerts', sa.Column('last_triggered', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('usage_alerts', sa.Column('alert_recipients', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('usage_alerts', sa.Column('threshold_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usage_alerts', type_='foreignkey')
    op.drop_column('usage_alerts', 'acknowledged_by')
    op.drop_column('usage_alerts', 'acknowledged')
    op.drop_column('usage_alerts', 'alert_date')
    op.drop_column('usage_alerts', 'current_value')
    op.drop_column('usage_alerts', 'threshold_value')
    op.drop_constraint('uq_uom_abbrev_company', 'unit_of_measures', type_='unique')
    op.drop_index('ix_uom_company', table_name='unit_of_measures')
    op.drop_index('ix_company_base_unit', table_name='unit_of_measures', postgresql_where=sa.text('is_base_unit'))
    op.drop_column('unit_of_measures', 'is_base_unit')
    op.drop_index('idx_supplier_company_active', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_supplier_code'), table_name='suppliers')
    op.create_index(op.f('ix_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=True)
    op.add_column('sales_orders', sa.Column('foreign_currency_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('sales_orders', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sales_orders', sa.Column('base_currency_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('sales_orders', sa.Column('exchange_rate', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sales_orders_currency_id_fkey'), 'sales_orders', 'currencies', ['currency_id'], ['id'])
    op.drop_constraint('uq_so_doc_number_company', 'sales_orders', type_='unique')
    op.drop_index('ix_so_company_status', table_name='sales_orders')
    op.drop_index('ix_so_company_date', table_name='sales_orders')
    op.drop_index('ix_so_company_customer', table_name='sales_orders')
    op.alter_column('sales_orders', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sales_orders', 'total_amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.add_column('sales_order_lines', sa.Column('base_currency_tax_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('resource_usage', sa.Column('usage_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('resource_usage', sa.Column('billing_period', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_company_resource_date', 'resource_usage', type_='unique')
    op.create_unique_constraint(op.f('uq_usage_company_resource_date'), 'resource_usage', ['company_id', 'resource_type', 'usage_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_resource_usage_billing_period'), 'resource_usage', ['billing_period'], unique=False)
    op.drop_column('resource_usage', 'created_at')
    op.drop_column('resource_usage', 'unit')
    op.drop_column('resource_usage', 'quantity')
    op.add_column('report_templates', sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('report_templates', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('report_templates', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('report_templates', 'report_type',
               existing_type=sa.Enum('BALANCE_SHEET', 'INCOME_STATEMENT', 'CASH_FLOW', 'TRIAL_BALANCE', 'CUSTOM', 'AR_AGING', 'AP_AGING', 'INVENTORY_VALUATION', name='reporttype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('report_templates', 'is_system')
    op.drop_column('report_templates', 'configuration')
    op.add_column('report_schedules', sa.Column('last_run_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('report_schedules', sa.Column('report_template_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('report_schedules', sa.Column('schedule_parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('report_schedules', sa.Column('schedule_frequency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('report_schedules', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('report_schedules', sa.Column('next_run_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'report_schedules', type_='foreignkey')
    op.create_foreign_key(op.f('report_schedules_report_template_id_fkey'), 'report_schedules', 'report_templates', ['report_template_id'], ['id'])
    op.drop_column('report_schedules', 'next_run_at')
    op.drop_column('report_schedules', 'last_run_at')
    op.drop_column('report_schedules', 'export_formats')
    op.drop_column('report_schedules', 'recipient_emails')
    op.drop_column('report_schedules', 'schedule_config')
    op.drop_column('report_schedules', 'frequency')
    op.drop_column('report_schedules', 'template_id')
    op.add_column('purchase_orders', sa.Column('foreign_currency_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('base_currency_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('exchange_rate', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('purchase_orders_currency_id_fkey'), 'purchase_orders', 'currencies', ['currency_id'], ['id'])
    op.drop_constraint('uq_po_doc_number_company', 'purchase_orders', type_='unique')
    op.drop_index('ix_po_company_supplier', table_name='purchase_orders')
    op.drop_index('ix_po_company_status', table_name='purchase_orders')
    op.drop_index('ix_po_company_date', table_name='purchase_orders')
    op.alter_column('purchase_orders', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.add_column('purchase_order_lines', sa.Column('base_currency_tax_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('pos_transactions', sa.Column('change_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('pos_transactions', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('pos_transactions', sa.Column('subtotal_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('pos_transactions', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pos_transactions', sa.Column('transaction_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('pos_transactions', sa.Column('cash_tendered', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pos_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('pos_transactions_session_id_fkey'), 'pos_transactions', 'pos_sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'pos_transactions', type_='unique')
    op.create_unique_constraint(op.f('uq_postrans_number_company'), 'pos_transactions', ['transaction_number', 'company_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('pos_transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pos_transactions', 'discount_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('pos_transactions', 'tax_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.drop_column('pos_transactions', 'receipt_email_sent')
    op.drop_column('pos_transactions', 'receipt_printed')
    op.drop_column('pos_transactions', 'payment_details')
    op.drop_column('pos_transactions', 'subtotal')
    op.drop_column('pos_transactions', 'transaction_date')
    op.drop_column('pos_transactions', 'till_session_id')
    op.add_column('pos_transaction_types', sa.Column('affects_inventory', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pos_transaction_types', sa.Column('affects_ar', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pos_transaction_types', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pos_transaction_types', type_='foreignkey')
    op.drop_constraint('uq_pos_trans_type_company', 'pos_transaction_types', type_='unique')
    op.create_unique_constraint(op.f('uq_postranstype_name_company'), 'pos_transaction_types', ['name', 'company_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('pos_transaction_types', 'gl_account_id')
    op.add_column('pos_transaction_lines', sa.Column('barcode_used', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('pos_transaction_lines', 'quantity',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=15, scale=3),
               existing_nullable=False)
    op.add_column('pos_defaults', sa.Column('default_sale_transaction_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pos_defaults', sa.Column('enable_negative_stock', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pos_defaults', sa.Column('default_return_transaction_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pos_defaults', sa.Column('default_customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pos_defaults', sa.Column('next_transaction_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pos_defaults', type_='foreignkey')
    op.create_foreign_key(op.f('pos_defaults_default_sale_transaction_type_id_fkey'), 'pos_defaults', 'pos_transaction_types', ['default_sale_transaction_type_id'], ['id'])
    op.create_foreign_key(op.f('pos_defaults_default_return_transaction_type_id_fkey'), 'pos_defaults', 'pos_transaction_types', ['default_return_transaction_type_id'], ['id'])
    op.create_foreign_key(op.f('pos_defaults_default_customer_id_fkey'), 'pos_defaults', 'customers', ['default_customer_id'], ['id'])
    op.create_index(op.f('ix_pos_defaults_id'), 'pos_defaults', ['id'], unique=False)
    op.drop_column('pos_defaults', 'cash_rounding_precision')
    op.drop_column('pos_defaults', 'allow_negative_stock')
    op.drop_column('pos_defaults', 'default_walk_in_customer_id')
    op.drop_constraint(None, 'pos_cash_movements', type_='foreignkey')
    op.create_foreign_key(op.f('pos_cash_movements_session_id_fkey'), 'pos_cash_movements', 'pos_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_platform_audit_logs_timestamp'), table_name='platform_audit_logs')
    op.drop_index(op.f('ix_platform_audit_logs_action'), table_name='platform_audit_logs')
    op.drop_index('idx_platform_audit_user_timestamp', table_name='platform_audit_logs')
    op.drop_index('idx_platform_audit_company_timestamp', table_name='platform_audit_logs')
    op.create_index(op.f('idx_platform_audit_logs_user_id'), 'platform_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_platform_audit_logs_timestamp'), 'platform_audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_platform_audit_logs_company_id'), 'platform_audit_logs', ['company_id'], unique=False)
    op.alter_column('platform_audit_logs', 'user_agent',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'order_defaults', type_='foreignkey')
    op.drop_constraint(None, 'order_defaults', type_='foreignkey')
    op.drop_column('order_defaults', 'order_approval_limit')
    op.drop_column('order_defaults', 'require_approval_for_orders')
    op.drop_column('order_defaults', 'grv_number_prefix')
    op.drop_column('order_defaults', 'purchase_order_number_prefix')
    op.drop_column('order_defaults', 'sales_order_number_prefix')
    op.drop_column('order_defaults', 'auto_generate_order_numbers')
    op.drop_column('order_defaults', 'default_warehouse_id')
    op.drop_column('order_defaults', 'default_sales_representative_id')
    op.drop_column('order_defaults', 'default_payment_terms')
    op.drop_column('order_defaults', 'default_currency_code')
    op.alter_column('manufacturing_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_barcode_company', 'item_barcodes', type_='unique')
    op.drop_index('ix_barcode_company', table_name='item_barcodes')
    op.create_unique_constraint(op.f('uq_itembarcode_company'), 'item_barcodes', ['barcode', 'company_id'], postgresql_nulls_not_distinct=False)
    op.add_column('inventory_transactions', sa.Column('foreign_currency_total_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('foreign_currency_unit_cost', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('exchange_rate', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('base_currency_unit_cost', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('base_currency_total_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('inventory_transactions_currency_id_fkey'), 'inventory_transactions', 'currencies', ['currency_id'], ['id'])
    op.drop_index('ix_inv_trans_company_warehouse', table_name='inventory_transactions')
    op.drop_index('ix_inv_trans_company_item', table_name='inventory_transactions')
    op.drop_index('ix_inv_trans_company_date', table_name='inventory_transactions')
    op.alter_column('inventory_transactions', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_inv_trans_type_name_company', 'inventory_transaction_types', type_='unique')
    op.drop_index('ix_inv_trans_type_company', table_name='inventory_transaction_types')
    op.create_unique_constraint(op.f('uq_invtranstype_name_company'), 'inventory_transaction_types', ['name', 'company_id'], postgresql_nulls_not_distinct=False)
    op.add_column('inventory_items', sa.Column('default_purchase_tax_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inventory_items', sa.Column('default_sales_tax_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('inventory_items_default_purchase_tax_type_id_fkey'), 'inventory_items', 'tax_types', ['default_purchase_tax_type_id'], ['id'])
    op.create_foreign_key(op.f('inventory_items_default_sales_tax_type_id_fkey'), 'inventory_items', 'tax_types', ['default_sales_tax_type_id'], ['id'])
    op.drop_constraint('uq_item_code_company', 'inventory_items', type_='unique')
    op.drop_index('ix_item_company_code', table_name='inventory_items')
    op.drop_index('ix_item_company_active', table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_code'), table_name='inventory_items')
    op.create_unique_constraint(op.f('uq_inventoryitem_code_company'), 'inventory_items', ['item_code', 'company_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_item_location_company_item', table_name='inventory_item_locations')
    op.drop_index('ix_item_location_company', table_name='inventory_item_locations')
    op.drop_constraint(None, 'inventory_defaults', type_='foreignkey')
    op.drop_column('inventory_defaults', 'default_grv_clearing_gl_account_id')
    op.drop_index('ix_count_session_company', table_name='inventory_count_sessions')
    op.alter_column('inventory_count_sessions', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_grv_doc_number_company', 'goods_received_vouchers', type_='unique')
    op.drop_index('ix_grv_company_supplier', table_name='goods_received_vouchers')
    op.drop_index('ix_grv_company_status', table_name='goods_received_vouchers')
    op.drop_index('ix_grv_company_date', table_name='goods_received_vouchers')
    op.alter_column('goods_received_vouchers', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'gl_transaction_types', type_='foreignkey')
    op.drop_constraint(None, 'gl_transaction_types', type_='foreignkey')
    op.drop_index(op.f('ix_gl_transaction_types_name'), table_name='gl_transaction_types')
    op.drop_index('idx_gl_trans_type_company', table_name='gl_transaction_types')
    op.drop_column('gl_transaction_types', 'tax_type_id')
    op.drop_column('gl_transaction_types', 'tax_calculation_method')
    op.drop_column('gl_transaction_types', 'tax_rate')
    op.drop_column('gl_transaction_types', 'is_tax_applicable')
    op.drop_column('gl_transaction_types', 'default_tax_control_account_id')
    op.drop_column('gl_journal_entry_lines', 'tax_base_amount')
    op.drop_column('gl_journal_entry_lines', 'is_tax_line')
    op.drop_constraint(None, 'gl_journal_entries', type_='foreignkey')
    op.drop_constraint(None, 'gl_journal_entries', type_='foreignkey')
    op.drop_index(op.f('ix_gl_journal_entries_entry_date'), table_name='gl_journal_entries')
    op.drop_index(op.f('ix_gl_journal_entries_company_id'), table_name='gl_journal_entries')
    op.alter_column('gl_journal_entries', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('gl_journal_entries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('gl_journal_entries', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('gl_journal_entries', 'approval_date')
    op.drop_column('gl_journal_entries', 'approved_by_user_id')
    op.drop_column('gl_journal_entries', 'posting_date')
    op.drop_column('gl_journal_entries', 'transaction_type_id')
    op.drop_index(op.f('ix_gl_accounts_company_id'), table_name='gl_accounts')
    op.drop_column('gl_accounts', 'updated_at')
    op.drop_column('gl_accounts', 'created_at')
    op.drop_index('idx_customer_company_balance', table_name='customers')
    op.drop_index('idx_customer_company_active', table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_foreign_key(op.f('fk_companies_created_by_user'), 'companies', 'users', ['created_by_user_id'], ['id'])
    op.create_index(op.f('idx_company_code'), 'companies', ['code'], unique=False)
    op.add_column('bom_defaults', sa.Column('default_scrap_gl_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bom_defaults', sa.Column('default_material_usage_gl_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bom_defaults', sa.Column('default_manufacturing_overhead_gl_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bom_defaults', sa.Column('default_wip_gl_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bom_defaults', sa.Column('next_mo_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bom_defaults', type_='foreignkey')
    op.drop_constraint(None, 'bom_defaults', type_='foreignkey')
    op.drop_constraint(None, 'bom_defaults', type_='foreignkey')
    op.drop_constraint(None, 'bom_defaults', type_='foreignkey')
    op.create_foreign_key(op.f('bom_defaults_default_scrap_gl_account_id_fkey'), 'bom_defaults', 'gl_accounts', ['default_scrap_gl_account_id'], ['id'])
    op.create_foreign_key(op.f('bom_defaults_default_wip_gl_account_id_fkey'), 'bom_defaults', 'gl_accounts', ['default_wip_gl_account_id'], ['id'])
    op.create_foreign_key(op.f('bom_defaults_default_material_usage_gl_account_id_fkey'), 'bom_defaults', 'gl_accounts', ['default_material_usage_gl_account_id'], ['id'])
    op.create_foreign_key(op.f('bom_defaults_default_manufacturing_overhead_gl_account_id_fkey'), 'bom_defaults', 'gl_accounts', ['default_manufacturing_overhead_gl_account_id'], ['id'])
    op.drop_column('bom_defaults', 'allow_negative_inventory')
    op.drop_column('bom_defaults', 'auto_issue_components')
    op.drop_column('bom_defaults', 'variance_gl_account_id')
    op.drop_column('bom_defaults', 'overhead_gl_account_id')
    op.drop_column('bom_defaults', 'labor_gl_account_id')
    op.drop_column('bom_defaults', 'wip_gl_account_id')
    op.drop_column('bom_defaults', 'default_labor_rate_per_hour')
    op.drop_column('bom_defaults', 'default_overhead_percentage')
    op.add_column('bom_components', sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('bom_components', 'unit_of_measure_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('billing_transactions', sa.Column('stripe_charge_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('idx_billing_transaction_stripe_invoice', table_name='billing_transactions')
    op.drop_index('idx_billing_transaction_company', table_name='billing_transactions')
    op.create_index(op.f('idx_billing_transaction_company_period'), 'billing_transactions', ['company_id', 'billing_period'], unique=False)
    op.alter_column('billing_transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('billing_transactions', 'billing_period',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('billing_transactions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.add_column('billing_configurations', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('billing_configurations', sa.Column('per_transaction_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('billing_configurations', sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('billing_configurations', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('billing_configurations', sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('billing_configurations', sa.Column('billing_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('billing_configurations', sa.Column('per_gb_storage_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('billing_configurations', sa.Column('base_monthly_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('billing_configurations', sa.Column('per_user_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('billing_configurations', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('billing_configurations', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_billing_config_company'), 'billing_configurations', ['company_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('billing_configurations', 'discount_percentage')
    op.drop_column('billing_configurations', 'custom_pricing')
    op.drop_column('billing_configurations', 'next_billing_date')
    op.drop_column('billing_configurations', 'payment_method_id')
    op.drop_column('billing_configurations', 'subscription_id')
    op.drop_column('billing_configurations', 'customer_id')
    op.drop_column('billing_configurations', 'billing_provider')
    op.drop_index('idx_ar_trans_company_open', table_name='ar_transactions')
    op.drop_index('idx_ar_trans_company_date', table_name='ar_transactions')
    op.drop_index('idx_ar_trans_company_customer', table_name='ar_transactions')
    op.drop_column('ar_defaults', 'default_credit_limit')
    op.drop_column('ar_defaults', 'default_payment_terms')
    op.drop_index('idx_ap_trans_company_supplier', table_name='ap_transactions')
    op.drop_index('idx_ap_trans_company_open', table_name='ap_transactions')
    op.drop_index('idx_ap_trans_company_date', table_name='ap_transactions')
    op.create_table('tills',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tills_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('till_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('till_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('default_cashier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('default_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cash_gl_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cash_gl_account_id'], ['gl_accounts.id'], name='tills_cash_gl_account_id_fkey'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='tills_company_id_fkey'),
    sa.ForeignKeyConstraint(['default_cashier_id'], ['users.id'], name='tills_default_cashier_id_fkey'),
    sa.ForeignKeyConstraint(['default_warehouse_id'], ['warehouses.id'], name='tills_default_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tills_pkey'),
    sa.UniqueConstraint('till_code', 'company_id', name='uq_till_code_company', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tills_id'), 'tills', ['id'], unique=False)
    op.create_table('pos_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('till_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cashier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('opening_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('closing_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('opening_cash', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('closing_cash', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('expected_cash', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('cash_variance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], name=op.f('pos_sessions_cashier_id_fkey')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('pos_sessions_company_id_fkey')),
    sa.ForeignKeyConstraint(['till_id'], ['tills.id'], name=op.f('pos_sessions_till_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pos_sessions_pkey'))
    )
    op.create_index(op.f('ix_pos_sessions_id'), 'pos_sessions', ['id'], unique=False)
    op.drop_index(op.f('ix_pos_payments_id'), table_name='pos_payments')
    op.drop_table('pos_payments')
    op.drop_index(op.f('ix_till_reconciliations_id'), table_name='till_reconciliations')
    op.drop_table('till_reconciliations')
    op.drop_index(op.f('ix_pos_till_sessions_id'), table_name='pos_till_sessions')
    op.drop_table('pos_till_sessions')
    op.drop_index(op.f('ix_pos_tills_id'), table_name='pos_tills')
    op.drop_table('pos_tills')
    op.drop_index(op.f('ix_generated_reports_id'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_feedback_comments_id'), table_name='feedback_comments')
    op.drop_index('ix_comment_user', table_name='feedback_comments')
    op.drop_index('ix_comment_request', table_name='feedback_comments')
    op.drop_table('feedback_comments')
    op.drop_index(op.f('ix_platform_invoices_id'), table_name='platform_invoices')
    op.drop_table('platform_invoices')
    op.drop_index('ix_feedback_user', table_name='feedback_requests')
    op.drop_index(op.f('ix_feedback_requests_id'), table_name='feedback_requests')
    op.drop_index('ix_feedback_company_type', table_name='feedback_requests')
    op.drop_index('ix_feedback_company_status', table_name='feedback_requests')
    op.drop_index('ix_feedback_company_module', table_name='feedback_requests')
    op.drop_index('ix_feedback_assigned', table_name='feedback_requests')
    op.drop_table('feedback_requests')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_created', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_company_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_usage_metrics_metric_date'), table_name='usage_metrics')
    op.drop_index(op.f('ix_usage_metrics_id'), table_name='usage_metrics')
    op.drop_index(op.f('ix_usage_metrics_created_at'), table_name='usage_metrics')
    op.drop_table('usage_metrics')
    op.drop_index(op.f('ix_system_configurations_key'), table_name='system_configurations')
    op.drop_index(op.f('ix_system_configurations_id'), table_name='system_configurations')
    op.drop_table('system_configurations')
    op.drop_index(op.f('ix_financial_reporting_periods_id'), table_name='financial_reporting_periods')
    op.drop_table('financial_reporting_periods')
    op.drop_index(op.f('ix_feedback_categories_id'), table_name='feedback_categories')
    op.drop_index('ix_category_company', table_name='feedback_categories')
    op.drop_table('feedback_categories')
    op.drop_index(op.f('ix_company_subscriptions_id'), table_name='company_subscriptions')
    op.drop_table('company_subscriptions')
    op.drop_index(op.f('ix_system_health_id'), table_name='system_health')
    op.drop_index(op.f('ix_system_health_checked_at'), table_name='system_health')
    op.drop_table('system_health')
    op.drop_index(op.f('ix_production_entries_placeholder_id'), table_name='production_entries_placeholder')
    op.drop_table('production_entries_placeholder')
    op.drop_index(op.f('ix_platform_admins_id'), table_name='platform_admins')
    op.drop_index(op.f('ix_platform_admins_email'), table_name='platform_admins')
    op.drop_table('platform_admins')
    op.drop_index(op.f('ix_material_requisitions_placeholder_id'), table_name='material_requisitions_placeholder')
    op.drop_table('material_requisitions_placeholder')
    op.drop_index(op.f('ix_feature_flags_name'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_id'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_billing_plans_id'), table_name='billing_plans')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###
